// gh-1192 — release-flow race hardening (2026-10-03 incident, issue #1189).
//
// Two independent defects:
//   Defect A — daily-publish's pub.dev verify had no «release in flight»
//     class: between `git push <tag>` and the tag's ci.yml run becoming
//     visible/completing, the check read «no run» and false-errored —
//     auto-filing #1189 one minute before the healthy tag run completed.
//     The classification now lives in scripts/verify_pubdev_release.sh.
//   Defect B — tag_release.sh tagged current main HEAD, so a commit landing
//     between the bump push and the tag job got captured inside the version
//     tag (v1.0.498 pointed at the #1178 interloper, not the bump).
//
// Behavioral coverage follows the release_hygiene_test.dart style: fixture
// git repos (bare origin + clones) and stubbed `gh`/`curl` on PATH. Git
// resolves to the real binary — the session PATH may carry shims
// (git-push-guard) that must never decide fixture behavior.
import 'dart:io';

import 'package:test/test.dart';

String read(String path) => File(path).readAsStringSync();

final _fixtureRoot = Directory.systemTemp.createTempSync('release-race-');

/// The real git binary for sandbox shims AND fixture helpers: the session
/// PATH may carry git-push-guard.sh shims — skip any copy of those plus
/// [skipDir] (the sandbox's own shim dir) so every git call resolves to a
/// real binary (same defense as release_hygiene_test.dart).
String _resolveRealGit([String? skipDir]) {
  for (final dir in (Platform.environment['PATH'] ?? '').split(':')) {
    if (dir.isEmpty || dir == skipDir) continue;
    final cand = '$dir/git';
    if (!File(cand).existsSync()) continue;
    final resolved = File(cand).resolveSymbolicLinksSync();
    if (resolved.endsWith('git-push-guard.sh')) continue;
    return resolved;
  }
  return '/usr/bin/git';
}

void _git(
  List<String> args, {
  String? cwd,
  Map<String, String> env = const {},
}) {
  final r = Process.runSync(_resolveRealGit(), args,
      workingDirectory: cwd, environment: env);
  if (r.exitCode != 0) fail('fixture git $args failed: ${r.stderr}');
}

String _gitOut(List<String> args, {String? cwd}) {
  final r = Process.runSync(_resolveRealGit(), args, workingDirectory: cwd);
  if (r.exitCode != 0) fail('fixture git $args failed: ${r.stderr}');
  return r.stdout.toString().trim();
}

int _epoch(DateTime t) => t.millisecondsSinceEpoch ~/ 1000;

/// Stub `bin/` dir: pass-through `git` (the resolved real binary), canned
/// `curl` (serves the pub.dev package API from GH_STUB_DIR), and a `gh`
/// stub answering `run list`/`run view` from canned JSON while logging
/// every invocation.
class StubEnv {
  StubEnv(this.bin, this.realGit);
  final String bin; // prepend to PATH
  final String realGit; // exported as FA_REAL_GIT for the git shim
}

StubEnv _installStubs(String dir) {
  final bin = Directory('$dir/bin')..createSync(recursive: true);
  final realGit = _resolveRealGit(bin.path);

  File('${bin.path}/git').writeAsStringSync(r'''
#!/usr/bin/env bash
# #1368 fixture seam: a planted lsremote-fail-first marker makes the FIRST
# `git ls-remote --tags` fail (tag not visible yet) while later calls pass
# through — the tag «appears» during the appear-wait loop.
if [ "$1" = "ls-remote" ] && [ -n "$GH_STUB_DIR" ] \
    && [ -f "$GH_STUB_DIR/lsremote-fail-first" ]; then
  c="$GH_STUB_DIR/lsremote-count"
  n=$(cat "$c" 2>/dev/null || echo 0); n=$((n+1)); echo "$n" > "$c"
  [ "$n" -eq 1 ] && exit 1
fi
exec "$FA_REAL_GIT" "$@"
''');

  // gh-1299 flutter stub — cwd is always flutter_app/ (tag_release.sh does
  // `cd flutter_app && flutter pub get --enforce-lockfile`). `pub get`
  // regenerates the lockfile pin from pubspec.yaml; `pub get
  // --enforce-lockfile` VERIFIES the pin matches and fails with the real
  // exit-65 error text on drift. A FA_FLUTTER_FAIL marker file forces the
  // failure for the NG2 tag-refusal test.
  File('${bin.path}/flutter').writeAsStringSync(r'''
#!/usr/bin/env bash
case " $* " in
  *" pub get"*) ;;
  *) echo "flutter-stub: unexpected invocation: $*" >&2; exit 64 ;;
esac
if [ -f "${FA_FLUTTER_FAIL:-}" ]; then
  echo "Unable to satisfy \`pubspec.yaml\` using \`pubspec.lock\`. (stub)" >&2
  exit 65
fi
ver=$(sed -n 's/^version: \([0-9.]*\)+.*/\1/p' pubspec.yaml)
if printf '%s\n' "$*" | grep -q -- --enforce-lockfile; then
  pinned=$(sed -n 's/^version: "\(.*\)"$/\1/p' pubspec.lock 2>/dev/null | tail -1)
  if [ "$pinned" != "$ver" ]; then
    echo "Unable to satisfy \`pubspec.yaml\` using \`pubspec.lock\`." >&2
    echo "To update \`pubspec.lock\` run \`flutter pub get\` without" >&2
    echo "\`--enforce-lockfile\`." >&2
    echo "Failed to update packages." >&2
    exit 65
  fi
  exit 0
fi
printf '# Generated by pub (sandbox stub)\nversion: "%s"\n' "$ver" > pubspec.lock
''');

  // pub.dev package API: before the tag-run rerun lands, pub.dev serves the
  // OLD version; once $GH_STUB_DIR/rerun-done exists (planted by the gh
  // stub's `run rerun`), it serves the new one. A $GH_STUB_DIR/curl-fail
  // marker simulates an API outage; every invocation is logged to curl.log
  // so tests can assert the read happened (or never did).
  File('${bin.path}/curl').writeAsStringSync('''
#!/usr/bin/env bash
echo "\$*" >> "\$GH_STUB_DIR/curl.log"
if [ -f "\$GH_STUB_DIR/curl-fail" ]; then
  echo "curl: simulated pub.dev API failure" >&2
  exit 1
fi
if [ -f "\$GH_STUB_DIR/rerun-done" ] && [ -f "\$GH_STUB_DIR/pubdev-new.json" ]; then
  cat "\$GH_STUB_DIR/pubdev-new.json"
else
  cat "\$GH_STUB_DIR/pubdev.json"
fi
''');

  File('${bin.path}/gh').writeAsStringSync(r'''
#!/usr/bin/env bash
echo "$*" >> "$GH_LOG_FILE"
cmd="$1"; shift || true
case "$cmd" in
  run)
    sub="$1"; shift || true
    case "$sub" in
      list)
        branch=""; jqf="."
        while [ $# -gt 0 ]; do
          case "$1" in
            --branch) branch="$2"; shift 2 ;;
            --jq) jqf="$2"; shift 2 ;;
            *) shift ;;
          esac
        done
        # Nth read of the same branch: runs-<branch>.N.json overrides the
        # base fixture when present — the past-grace re-read test (review
        # thread 2) plants a run on the SECOND read.
        cf="$GH_STUB_DIR/list-count-$branch"
        n=$(cat "$cf" 2>/dev/null || echo 0); n=$((n+1)); echo "$n" > "$cf"
        f="$GH_STUB_DIR/runs-$branch.$n.json"
        [ -f "$f" ] || f="$GH_STUB_DIR/runs-$branch.json"
        [ -f "$f" ] || f="$GH_STUB_DIR/runs.json"
        [ -f "$f" ] || { echo "stub: no fixture for branch '$branch'" >&2; exit 1; }
        jq -r "$jqf" "$f"
        ;;
      view)
        id="$1"; shift || true
        jqf="."
        while [ $# -gt 0 ]; do
          case "$1" in --jq) jqf="$2"; shift 2 ;; *) shift ;; esac
        done
        # Nth read of the same run: run-<id>.N.json overrides the base
        # fixture when present — the terminal-wait tests plant a queued
        # first read and a completed later one (#1368).
        cf="$GH_STUB_DIR/view-count-$id"
        n=$(cat "$cf" 2>/dev/null || echo 0); n=$((n+1)); echo "$n" > "$cf"
        f="$GH_STUB_DIR/run-$id.$n.json"
        [ -f "$f" ] || f="$GH_STUB_DIR/run-$id.json"
        if [ -f "$GH_STUB_DIR/rerun-done" ] && [ -f "$GH_STUB_DIR/run-$id-post.json" ]; then
          f="$GH_STUB_DIR/run-$id-post.json"
        fi
        [ -f "$f" ] || { echo "stub: no fixture for run '$id'" >&2; exit 1; }
        jq -r "$jqf" "$f"
        ;;
      watch) exit 0 ;;
      rerun) touch "$GH_STUB_DIR/rerun-done"; exit 0 ;;
      *) exit 0 ;;
    esac
    ;;
  label) exit 0 ;;
  issue)
    case "$1" in
      list) cat "$GH_STUB_DIR/issues.tsv" 2>/dev/null; exit 0 ;;
      close|comment|create) echo "https://github.com/OWNER/REPO/issues/99" ;;
      *) exit 0 ;;
    esac
    ;;
  release)
    # tag_release.sh's GitHub Release creation — expected, quiet success.
    exit 0 ;;
  *)
    # gh-1192 review thread 3: a silently-swallowed unknown subcommand lets
    # script drift read green (a grown `gh api` call would no-op and every
    # fixture stays vacuous). Fail loudly so drift turns into a red test.
    echo "stub: unexpected gh invocation: $*" >&2
    exit 1 ;;
esac
''');

  for (final f in ['git', 'curl', 'gh', 'flutter']) {
    Process.runSync('chmod', ['+x', '${bin.path}/$f']);
  }
  return StubEnv(bin.path, realGit);
}

Map<String, String> _parseOutputs(String path) {
  final out = <String, String>{};
  for (final line in File(path).readAsLinesSync()) {
    final i = line.indexOf('=');
    if (i > 0) out[line.substring(0, i)] = line.substring(i + 1);
  }
  return out;
}

class VerifyRun {
  VerifyRun(this.exitCode, this.output, this.outputs, this.ghLog);

  final int exitCode;
  final String output; // stdout+stderr
  final Map<String, String> outputs; // GITHUB_OUTPUT key=values
  final List<String> ghLog; // stubbed gh invocations

  String get status => outputs['status'] ?? '';
  bool get errored => output.contains('::error::');
  bool get inFlight => status == 'release-in-flight' && exitCode == 0;
}

/// Full sandbox for scripts/verify_pubdev_release.sh (the daily-publish
/// pubdev leg's check): a bare origin whose main carries `version:
/// [version]` in a commit named [bumpSubject] backdated [bumpAge], an
/// optional annotated tag `v[version]` backdated [tagAge] (the annotated
/// tagger date is what %(creatordate:unix) reads back), a job clone the
/// script runs in, and stub gh/curl fixtures. [runsJson] is what
/// `gh run list --branch v<version>` serves ('[]' = the run is not visible
/// yet); [secondReadJson] overrides the SECOND read of that branch (the
/// past-grace re-read, review thread 2); [conclusion] is the completed
/// run's conclusion (served once the stub sees the run id);
/// [rerunToSuccess] makes the post-rerun view green.
VerifyRun runVerify(
  String name, {
  String version = '0.1.497',
  String publishedVersion = '0.1.496',
  bool tagPresent = true,
  Duration tagAge = const Duration(seconds: 60),
  String bumpSubject = 'chore(release): v0.1.497',
  Duration bumpAge = const Duration(seconds: 90),
  int commitsOnTop = 0, // ordinary PRs that landed on main after the bump
  bool publishToNone = false,
  String? runsJson = '[]',
  String? secondReadJson,
  String conclusion = 'success',
  bool rerunToSuccess = false,
  // #1368 fixture seams: the FIRST `git ls-remote --tags` fails (the tag is
  // not visible yet) while later calls see the tag; the run-view Nth-read
  // override (run-<id>.1.json) serves a queued status before the base
  // completed one — the terminal-wait flip.
  bool lsremoteFailFirst = false,
  String? firstViewJson,
  Map<String, String> extraEnv = const {},
}) {
  final dir = Directory(
          '${_fixtureRoot.path}/verify-$name-${DateTime.now().microsecondsSinceEpoch}')
    ..createSync(recursive: true);
  final origin = '${dir.path}/origin.git';
  final seed = '${dir.path}/seed';
  final job = '${dir.path}/job';
  final stub = _installStubs(dir.path);
  final now = DateTime.now().toUtc();

  Directory(origin).createSync();
  _git(['init', '-q', '--bare', '-b', 'main', origin], cwd: dir.path);
  _git(['clone', '-q', origin, seed], cwd: dir.path);
  _git(['config', 'user.email', 't@t'], cwd: seed);
  _git(['config', 'user.name', 't'], cwd: seed);
  File('$seed/pubspec.yaml').writeAsStringSync('name: demo\nversion: $version\n'
      '${publishToNone ? 'publish_to: none\n' : ''}');
  _git(['add', '-A'], cwd: seed);
  _git(['commit', '-q', '-m', bumpSubject], cwd: seed, env: {
    'GIT_COMMITTER_DATE': '${_epoch(now.subtract(bumpAge))}',
    'GIT_AUTHOR_DATE': '${_epoch(now.subtract(bumpAge))}',
  });
  for (var i = 1; i <= commitsOnTop; i++) {
    _git(['commit', '-q', '--allow-empty', '-m', 'feat: follow-up $i'], cwd: seed);
  }
  if (tagPresent) {
    _git(['tag', '-a', 'v$version', '-m', 'Release v$version'], cwd: seed,
        env: {
          'GIT_COMMITTER_DATE': '${_epoch(now.subtract(tagAge))}',
        });
    _git(['push', '-q', 'origin', 'refs/tags/v$version'], cwd: seed);
  }
  _git(['push', '-q', 'origin', 'main'], cwd: seed);
  // The daily's checkout is SHALLOW (actions/checkout default fetch-depth
  // 1) — file:// so git honors --depth on the local transport.
  _git(['clone', '-q', '--depth', '1', 'file://$origin', job], cwd: dir.path);

  File('${dir.path}/pubdev.json')
      .writeAsStringSync('{"latest":{"version":"$publishedVersion"}}');
  File('${dir.path}/pubdev-new.json')
      .writeAsStringSync('{"latest":{"version":"$version"}}');
  File('${dir.path}/runs-v$version.json').writeAsStringSync(runsJson ?? '[]');
  if (secondReadJson != null) {
    File('${dir.path}/runs-v$version.2.json').writeAsStringSync(secondReadJson);
  }
  if (lsremoteFailFirst) {
    File('${dir.path}/lsremote-fail-first').writeAsStringSync('');
  }

  // The run-view fixture mirrors EVERY listed run's status: a queued/
  // in_progress entry stays pending on `run view` (the terminal-wait polls
  // it); a completed one serves [conclusion]. With [firstViewJson] the FIRST
  // entry's first view serves that (still queued) and the base flips to
  // completed — the «reaches terminal within the wait» shape. Post-rerun,
  // the stub serves the -post.json success when [rerunToSuccess].
  void plantRun(String listJson) {
    if (listJson.isEmpty || listJson == '[]') return;
    final objs = RegExp(r'\{[^}]*\}')
        .allMatches(listJson)
        .map((m) => m.group(0)!)
        .toList();
    var first = true;
    for (final obj in objs) {
      final id = RegExp(r'"databaseId":\s*(\d+)').firstMatch(obj)?.group(1);
      if (id == null) continue;
      final listed =
          RegExp(r'"status":\s*"([^"]+)"').firstMatch(obj)?.group(1) ??
              'completed';
      final base = (firstViewJson != null && first) || listed == 'completed'
          ? '{"status":"completed","conclusion":"$conclusion"}'
          : '{"status":"$listed","conclusion":null}';
      File('${dir.path}/run-$id.json').writeAsStringSync(base);
      if (rerunToSuccess) {
        File('${dir.path}/run-$id-post.json')
            .writeAsStringSync('{"status":"completed","conclusion":"success"}');
      }
      if (firstViewJson != null && first) {
        File('${dir.path}/run-$id.1.json').writeAsStringSync(firstViewJson);
      }
      first = false;
    }
  }
  if (runsJson != null) plantRun(runsJson);
  if (secondReadJson != null) plantRun(secondReadJson);

  final outPath = '${dir.path}/github_output';
  final res = Process.runSync(
    'bash',
    [File('scripts/verify_pubdev_release.sh').absolute.path],
    workingDirectory: job,
    environment: {
      'PATH': '${stub.bin}:${Platform.environment['PATH']}',
      'FA_REAL_GIT': stub.realGit,
      'GITHUB_REPOSITORY': 'OWNER/REPO',
      'GH_TOKEN': 'stub',
      'GH_STUB_DIR': dir.path,
      'GH_LOG_FILE': '${dir.path}/gh.log',
      'GITHUB_OUTPUT': outPath,
      // Test seams — production defaults live in the script.
      'PUBDEV_READ_SLEEP_SECS': '0',
      'PUBDEV_POLL_SLEEP_SECS': '0',
      ...extraEnv,
    },
  );
  return VerifyRun(
    res.exitCode,
    '${res.stdout}${res.stderr}',
    File(outPath).existsSync() ? _parseOutputs(outPath) : {},
    File('${dir.path}/gh.log').existsSync()
        ? File('${dir.path}/gh.log').readAsLinesSync()
        : <String>[],
  );
}

class TagReleaseRun {
  TagReleaseRun(this.exitCode, this.output, this.ghLog, this.originDir,
      this.bumpSha, this.interloperSha);

  final int exitCode;
  final String output;
  final List<String> ghLog;
  final String originDir;
  final String bumpSha; // the chore(release) commit the tag must pin
  final String? interloperSha; // the commit that raced onto main after it

  /// The commit `v[version]` points at in origin, or null when absent.
  String? tagCommit(String version) {
    final r = Process.runSync(_resolveRealGit(), [
      '--git-dir',
      originDir,
      'rev-parse',
      '-q',
      '--verify',
      'refs/tags/v$version^{commit}',
    ]);
    return r.exitCode == 0 ? r.stdout.toString().trim() : null;
  }

  String fileInTag(String version, String path) {
    final r = Process.runSync(
        _resolveRealGit(), ['--git-dir', originDir, 'show', 'v$version:$path']);
    if (r.exitCode != 0) fail('git show v$version:$path failed: ${r.stderr}');
    return r.stdout.toString();
  }
}

/// Sandbox for scripts/tag_release.sh reproducing Defect B: the seed clone
/// pushes the `chore(release): v0.1.496` bump, [interloper] lands an
/// unrelated commit on main afterwards (the #1178 FIFO capture), and the
/// job clone — the drifted release-tag checkout — runs the script with
/// [bumpShaEnv] as BUMP_SHA (null = the history-search fallback path).
TagReleaseRun runTagRelease(
  String name, {
  bool interloper = true,
  String? bumpShaEnv,
  bool preExistingTag = false,
  String seedSubject = 'chore(release): v0.1.496',
  bool lockfileFails = false,
  bool staleBumpLockfile = false,
}) {
  final dir = Directory(
          '${_fixtureRoot.path}/tagrel-$name-${DateTime.now().microsecondsSinceEpoch}')
    ..createSync(recursive: true);
  final origin = '${dir.path}/origin.git';
  final seed = '${dir.path}/seed';
  final racer = '${dir.path}/racer';
  final job = '${dir.path}/job';
  final stub = _installStubs(dir.path);

  Directory(origin).createSync();
  _git(['init', '-q', '--bare', '-b', 'main', origin], cwd: dir.path);
  _git(['clone', '-q', origin, seed], cwd: dir.path);
  _git(['config', 'user.email', 't@t'], cwd: seed);
  _git(['config', 'user.name', 't'], cwd: seed);
  File('$seed/pubspec.yaml').writeAsStringSync('name: demo\nversion: 0.1.495\n');
  File('$seed/CHANGELOG.md').writeAsStringSync('# Changelog\n\n## Unreleased\n');
  // gh-1299: the repo ships a COMMITTED flutter_app/pubspec.lock (the
  // #1265/#1268 enforce-lockfile shape) — the seed models it, and the bump
  // below carries it REFRESHED, exactly what the fixed auto_release.sh
  // ships and what the NG2 smoke in tag_release.sh verifies.
  Directory('$seed/flutter_app').createSync();
  File(
    '$seed/flutter_app/pubspec.yaml',
  ).writeAsStringSync('name: demo\nversion: 0.1.495+1\n');
  File('$seed/flutter_app/pubspec.lock').writeAsStringSync(
    '# Generated by pub (sandbox seed)\nversion: "0.1.495"\n',
  );
  _git(['add', '-A'], cwd: seed);
  _git(['commit', '-q', '-m', 'seed'], cwd: seed);
  _git(['tag', 'v0.1.495'], cwd: seed);
  _git(['push', '-q', 'origin', 'main', 'refs/tags/v0.1.495'], cwd: seed);

  // The bump — the commit the version tag must pin (gh-1192 AC3).
  File('$seed/pubspec.yaml').writeAsStringSync('name: demo\nversion: 0.1.496\n');
  File('$seed/CHANGELOG.md').writeAsStringSync(
      '# Changelog\n\n## 0.1.496\n\n- curated release note\n\n## Unreleased\n');
  File(
    '$seed/flutter_app/pubspec.yaml',
  ).writeAsStringSync('name: demo\nversion: 0.1.496+1\n');
  File('$seed/flutter_app/pubspec.lock').writeAsStringSync(
    staleBumpLockfile
        ? // gh-1299 NG2 refusal: the bump shipped WITHOUT the lockfile
          // refresh — the v1.0.515 shape the smoke must refuse to tag.
          '# Generated by pub (sandbox stub)\nversion: "0.1.495"\n'
        : '# Generated by pub (sandbox stub)\nversion: "0.1.496"\n',
  );
  _git(['add', '-A'], cwd: seed);
  _git(['commit', '-q', '-m', seedSubject], cwd: seed);
  _git(['push', '-q', 'origin', 'main'], cwd: seed);
  final bumpSha = _gitOut(['rev-parse', 'HEAD'], cwd: seed);

  String? interloperSha;
  if (interloper) {
    _git(['clone', '-q', origin, racer], cwd: dir.path);
    _git(['config', 'user.email', 't@t'], cwd: racer);
    _git(['config', 'user.name', 't'], cwd: racer);
    File('$racer/README.md')
        .writeAsStringSync('landed via the FIFO queue in the race window\n');
    _git(['add', '-A'], cwd: racer);
    _git(['commit', '-q', '-m', 'fix: unrelated interloper (#1178)'], cwd: racer);
    _git(['push', '-q', 'origin', 'main'], cwd: racer);
    interloperSha = _gitOut(['rev-parse', 'HEAD'], cwd: racer);
  }

  // The release-tag checkout: main AFTER the interloper — the drifted tree
  // the 2026-10-03 tag was cut from. The job clone needs its own identity:
  // the preExistingTag fixture tags FROM HERE, and CI runners have no
  // global git ident (validation run 37114132425 died on «Committer
  // identity unknown» — the seed/racer clones configure one, this missed it).
  _git(['clone', '-q', origin, job], cwd: dir.path);
  _git(['config', 'user.email', 't@t'], cwd: job);
  _git(['config', 'user.name', 't'], cwd: job);
  if (preExistingTag) {
    _git(['tag', '-a', 'v0.1.496', '-m', 'Release v0.1.496', bumpSha], cwd: job);
    _git(['push', '-q', 'origin', 'refs/tags/v0.1.496'], cwd: job);
  }

  final env = <String, String>{
    'PATH': '${stub.bin}:${Platform.environment['PATH']}',
    'FA_REAL_GIT': stub.realGit,
    'GITHUB_REPOSITORY': 'OWNER/REPO',
    'GH_TOKEN': 'stub',
    'GH_STUB_DIR': dir.path,
    'GH_LOG_FILE': '${dir.path}/gh.log',
    'FA_FLUTTER_FAIL': '${dir.path}/flutter-fail',
  };
  if (lockfileFails) File('${dir.path}/flutter-fail').writeAsStringSync('1');
  if (bumpShaEnv != null) env['BUMP_SHA'] = bumpShaEnv;

  final res = Process.runSync(
    'bash',
    [File('scripts/tag_release.sh').absolute.path],
    workingDirectory: job,
    environment: env,
  );
  return TagReleaseRun(
    res.exitCode,
    '${res.stdout}${res.stderr}',
    File('${dir.path}/gh.log').existsSync()
        ? File('${dir.path}/gh.log').readAsLinesSync()
        : <String>[],
    origin,
    bumpSha,
    interloperSha,
  );
}

class ReportRun {
  ReportRun(this.exitCode, this.output, this.ghLog, this.summary);
  final int exitCode;
  final String output;
  final List<String> ghLog;
  final String summary;
}

/// Runs scripts/daily_publish_report.sh with the pubdev leg green and the
/// release-in-flight status override — the AC1 «no auto-filed issue» end of
/// the pipeline (issue filing lives in the report job, not the leg).
ReportRun runReport(String name) {
  final dir = Directory(
          '${_fixtureRoot.path}/report-$name-${DateTime.now().microsecondsSinceEpoch}')
    ..createSync(recursive: true);
  final stub = _installStubs(dir.path);
  File('${dir.path}/issues.tsv').writeAsStringSync('');
  final summaryPath = '${dir.path}/summary.md';
  final res = Process.runSync(
    'bash',
    [File('scripts/daily_publish_report.sh').absolute.path],
    workingDirectory: dir.path,
    environment: {
      'PATH': '${stub.bin}:${Platform.environment['PATH']}',
      'FA_REAL_GIT': stub.realGit,
      'GITHUB_REPOSITORY': 'OWNER/REPO',
      'GITHUB_RUN_ID': '555',
      'GITHUB_SERVER_URL': 'https://github.com',
      'GH_TOKEN': 'stub',
      'GH_STUB_DIR': dir.path,
      'GH_LOG_FILE': '${dir.path}/gh.log',
      'GITHUB_STEP_SUMMARY': summaryPath,
      'NEXT_TAG': 'v0.1.498',
      'DAILY_PUBLISH_ASSIGNEE': 'ai-teammate',
      'LEG_TESTFLIGHT': 'skipped',
      'LEG_PLAY': 'skipped',
      'LEG_CLI': 'skipped',
      'LEG_WEBSITE': 'skipped',
      'LEG_ADDIN': 'skipped',
      'LEG_PUBDEV': 'success',
      'LEG_PUBDEV_STATUS': 'release-in-flight',
      'LEG_PUBDEV_PUBSPEC': '0.1.497',
      'LEG_PUBDEV_PUBLISHED': '0.1.496',
    },
  );
  return ReportRun(
    res.exitCode,
    '${res.stdout}${res.stderr}',
    File('${dir.path}/gh.log').existsSync()
        ? File('${dir.path}/gh.log').readAsLinesSync()
        : <String>[],
    File(summaryPath).existsSync() ? File(summaryPath).readAsStringSync() : '',
  );
}

class PlanRun {
  PlanRun(this.exitCode, this.output, this.outputs, this.ghLog, this.curlLog);
  final int exitCode;
  final String output;
  final Map<String, String> outputs; // GITHUB_OUTPUT key=values
  final List<String> ghLog; // stubbed gh invocations
  final List<String> curlLog; // stubbed curl invocations

  bool get changed => outputs['changed'] == 'true';
}

/// Sandbox for scripts/daily_plan.sh (the daily-publish plan job's
/// «Detect main movement and derive versions» step): an origin whose main
/// carries `version: [version]` plus an annotated latest tag one patch
/// below it, a FULL job clone (the plan job checks out with fetch-depth: 0,
/// so `git rev-parse origin/main` and the tag sort must resolve), the
/// shared gh/curl stubs, and a `gh run list --branch main` fixture.
/// [lastGreen]: 'head' — the newest successful scheduled daily ran at
/// main's current sha; 'older' — at an older sha (main moved); null — no
/// green all-legs daily recorded. [servedVersion] is what the pub.dev API
/// fixture serves; [pubdevApiDown] makes every curl fail (the re-arm must
/// fail OPEN, never block on an API outage).
PlanRun runPlan(
  String name, {
  String version = '0.1.497',
  String? lastGreen,
  bool force = false,
  String? servedVersion,
  bool pubdevApiDown = false,
}) {
  final dir = Directory(
          '${_fixtureRoot.path}/plan-$name-${DateTime.now().microsecondsSinceEpoch}')
    ..createSync(recursive: true);
  final origin = '${dir.path}/origin.git';
  final seed = '${dir.path}/seed';
  final job = '${dir.path}/job';
  final stub = _installStubs(dir.path);

  Directory(origin).createSync();
  _git(['init', '-q', '--bare', '-b', 'main', origin], cwd: dir.path);
  _git(['clone', '-q', origin, seed], cwd: dir.path);
  _git(['config', 'user.email', 't@t'], cwd: seed);
  _git(['config', 'user.name', 't'], cwd: seed);
  File('$seed/pubspec.yaml').writeAsStringSync('name: demo\nversion: $version\n');
  _git(['add', '-A'], cwd: seed);
  _git(['commit', '-q', '-m', 'chore(release): v$version'], cwd: seed);
  _git(['tag', '-a', 'v0.1.496', '-m', 'Release v0.1.496'], cwd: seed);
  _git(['push', '-q', 'origin', 'main', 'refs/tags/v0.1.496'], cwd: seed);
  final headSha = _gitOut(['rev-parse', 'HEAD'], cwd: seed);
  // The plan job's checkout is FULL (fetch-depth: 0) — origin/main and the
  // pushed tag must both resolve in the job clone.
  _git(['clone', '-q', origin, job], cwd: dir.path);

  File('${dir.path}/pubdev.json')
      .writeAsStringSync('{"latest":{"version":"${servedVersion ?? version}"}}');
  final green = switch (lastGreen) {
    null => '[]',
    'head' =>
      '[{"headSha":"$headSha","event":"schedule","displayTitle":"Daily"}]',
    _ =>
      '[{"headSha":"0000000000000000000000000000000000000000","event":"schedule","displayTitle":"Daily"}]',
  };
  File('${dir.path}/runs-main.json').writeAsStringSync(green);
  if (pubdevApiDown) File('${dir.path}/curl-fail').writeAsStringSync('');

  final outPath = '${dir.path}/github_output';
  final res = Process.runSync(
    'bash',
    [File('scripts/daily_plan.sh').absolute.path],
    workingDirectory: job,
    environment: {
      'PATH': '${stub.bin}:${Platform.environment['PATH']}',
      'FA_REAL_GIT': stub.realGit,
      'GITHUB_REPOSITORY': 'OWNER/REPO',
      'GH_TOKEN': 'stub',
      'GH_STUB_DIR': dir.path,
      'GH_LOG_FILE': '${dir.path}/gh.log',
      'GITHUB_OUTPUT': outPath,
      if (force) 'FORCE': 'true',
    },
  );
  return PlanRun(
    res.exitCode,
    '${res.stdout}${res.stderr}',
    File(outPath).existsSync() ? _parseOutputs(outPath) : {},
    File('${dir.path}/gh.log').existsSync()
        ? File('${dir.path}/gh.log').readAsLinesSync()
        : <String>[],
    File('${dir.path}/curl.log').existsSync()
        ? File('${dir.path}/curl.log').readAsLinesSync()
        : <String>[],
  );
}

void main() {
  // ── AC1/AC4 — «release in flight» is neutral, never an alarm ────────────
  group('AC1/AC4 — verify classifies release-in-flight, no ::error::', () {
    test(
      '2026-10-03 timeline: tag 60s old, tag-run not visible yet -> neutral skip',
      () {
        final r = runVerify('incident-timeline');
        expect(r.exitCode, 0, reason: r.output);
        expect(r.inFlight, isTrue, reason: r.output);
        expect(r.errored, isFalse, reason: 'the #1189 false-alarm class');
        expect(r.outputs['run_url'] ?? '', isEmpty,
            reason: 'no run exists to link');
        expect(r.output, contains('release in flight'));
        expect(
          r.ghLog.where((l) => l.contains('--branch v0.1.497')),
          hasLength(1),
          reason: 'the classification reads the tag-run list exactly once',
        );
      },
    );

    test('tag-run queued or in_progress -> skip, run linked', () {
      for (final status in ['queued', 'in_progress']) {
        final r = runVerify('run-$status',
            runsJson:
                '[{"databaseId":4242,"status":"$status","conclusion":null,"event":"push"}]',
            extraEnv: const {'PUBDEV_MAX_POLLS': '2'});
        expect(r.exitCode, 0, reason: r.output);
        expect(r.inFlight, isTrue, reason: r.output);
        expect(r.errored, isFalse, reason: r.output);
        expect(r.outputs['run_url'],
            'https://github.com/OWNER/REPO/actions/runs/4242');
      }
    });

    test('E1: run queued far past the grace window still skips, never alarms',
        () {
      final r = runVerify('starved-run',
          tagAge: const Duration(hours: 3),
          runsJson:
              '[{"databaseId":4242,"status":"queued","conclusion":null,"event":"push"}]',
          extraEnv: const {'PUBDEV_MAX_POLLS': '2'});
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
    });

    test('tag not cut yet + fresh bump on main -> skip (release-tag pending)',
        () {
      final r = runVerify('tag-pending',
          tagPresent: false, bumpAge: const Duration(seconds: 60));
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
    });

    test(
        'tag not cut yet + bump already buried under later commits -> still in flight',
        () {
      // The bump landed minutes ago; ordinary PRs landed on top of it while
      // release-tag's gate runs. The bump is no longer main's HEAD, but it
      // is reachable and fresh — the tag is merely pending.
      final r = runVerify('tag-pending-buried',
          tagPresent: false,
          commitsOnTop: 2,
          bumpAge: const Duration(seconds: 120));
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
    });

    test('grace is tunable (RELEASE_FLIGHT_GRACE_SECS): 2h-old tag inside a 3h grace skips',
        () {
      final r = runVerify('grace-knob',
          tagAge: const Duration(hours: 2),
          runsJson: '[]',
          extraEnv: {'RELEASE_FLIGHT_GRACE_SECS': '10800'});
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
    });
  });

  // ── AC2 — genuine trigger failure still alarms, unchanged text ──────────
  group('AC2 — genuine failures keep the existing alarm', () {
    const expectedError = 'v0.1.497 has no ci.yml run — the tag-publish never '
        'triggered (no run registered past the 900s grace window). Manual '
        'fix: re-push the tag (git push origin v0.1.497 --force) or run '
        'ci.yml on the tag ref.';

    test('tag past grace with NO run -> the exact current error text', () {
      final r = runVerify('expired-no-run',
          tagAge: const Duration(hours: 2), runsJson: '[]');
      expect(r.exitCode, isNot(0), reason: r.output);
      expect(r.errored, isTrue);
      expect(r.output, contains(expectedError));
      expect(
        r.ghLog.where((l) => l.contains('--branch v0.1.497')),
        hasLength(2),
        reason: 'the alarm fires only after one spaced re-read (review thread 2)',
      );
    });

    test(
        'review thread 2 (E4 residual): run registers between the reads -> '
        'the past-grace re-read finds it and the leg skips, never alarms', () {
      // An operator re-pushed the stale tag while the daily was between its
      // `git ls-remote` and the `gh run list`: the first read saw nothing,
      // the tag is past the grace — the old code false-errored here. The
      // re-read must find the fresh (queued) run and classify in-flight.
      final r = runVerify(
        'repush-second-read',
        tagAge: const Duration(hours: 2),
        runsJson: '[]',
        secondReadJson:
            '[{"databaseId":4242,"status":"queued","conclusion":null,"event":"push"}]',
        extraEnv: const {'PUBDEV_MAX_POLLS': '2'},
      );
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: 'the #1189 false-alarm class');
      expect(r.outputs['run_url'],
          'https://github.com/OWNER/REPO/actions/runs/4242');
      expect(
        r.ghLog.where((l) => l.contains('--branch v0.1.497')),
        hasLength(2),
        reason: 'exactly one spaced re-read, then the run governs (E1)',
      );
    });

    test('#1368: tag not cut + HOURS-old bump -> still pending, never «never triggered»', () {
      // The 2026-10-07 incident: the verify read a 10.5h-old bump at
      // 05:31:55 and false-errored «never triggered»; release-tag cut the
      // tag at 05:35:13. The ≥1h untagged state is auto-release's own
      // «proceed, the next range absorbs it» self-heal, not a wedged
      // publish — the old 1h horizon is gone; a bump (any age) is pending.
      final r = runVerify('old-bump-pending',
          tagPresent: false, bumpAge: const Duration(hours: 10, minutes: 33));
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: 'the #1368 false-alarm class');
      expect(r.output, contains('release-tag has not cut v0.1.497 yet'));
      expect(r.output, isNot(contains('never triggered')));
    });

    test('tag never cut + no bump commit on main at all -> alarm', () {
      final r = runVerify('untagged-no-bump',
          tagPresent: false,
          bumpSubject: 'feat: unrelated work, no release in flight',
          bumpAge: const Duration(seconds: 60));
      expect(r.exitCode, isNot(0), reason: r.output);
      expect(r.errored, isTrue);
      expect(r.output,
          contains('never triggered (no tag and no chore(release) bump on main)'));
    });

    test('completed run succeeded but pub.dev behind -> publish-did-not-upload alarm',
        () {
      final r = runVerify('success-but-behind',
          runsJson:
              '[{"databaseId":4242,"status":"completed","conclusion":"success","event":"push"}]');
      expect(r.exitCode, isNot(0), reason: r.output);
      expect(r.errored, isTrue);
      expect(r.output, contains('publish did not upload'));
      expect(r.ghLog.where((l) => l.contains('run rerun')), isEmpty,
          reason: 'a green run must not be rerun');
    });

    test('completed run failed -> the existing rerun recovery path fires', () {
      final r = runVerify('rerun-recovers',
          runsJson:
              '[{"databaseId":4242,"status":"completed","conclusion":"failure","event":"push"}]',
          conclusion: 'failure',
          rerunToSuccess: true);
      expect(r.exitCode, 0, reason: r.output);
      expect(r.status, 'recovered');
      expect(
        r.ghLog.where((l) => l.contains('run rerun 4242') && l.contains('--failed')),
        hasLength(1),
      );
    });

    test('E4: re-pushed OLD tag with a fresh run never reads «never triggered»',
        () {
      final r = runVerify('repushed-old-tag',
          tagAge: const Duration(hours: 2),
          runsJson:
              '[{"databaseId":4242,"status":"queued","conclusion":null,"event":"push"}]',
          extraEnv: const {'PUBDEV_MAX_POLLS': '2'});
      expect(r.exitCode, 0, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
      expect(r.output, isNot(contains('never triggered')),
          reason: 'the re-push manual fix path must keep working (E4)');
    });
  });

  // ── #1368 — twin-run selection, bounded waits, true-state errors ─────────
  group('#1368 — push-twin selection and the bounded waits', () {
    test('release-event-only runs past grace -> «never triggered», the exit-65 arm named',
        () {
      // The old release arm: the release twin attempted the publish pub.dev
      // OIDC always rejects. Its failure must read as never-published, and
      // recovery must never rerun THAT twin. The tag is aged past the 900s
      // grace (20 min) — INSIDE the grace the selection correctly keeps the
      // leg in the neutral in-flight class (pinned by the young-tag
      // companion case below); the alarm branch is grace-expired only.
      final r = runVerify('release-twin-only',
          tagAge: const Duration(minutes: 20),
          runsJson:
              '[{"databaseId":77,"status":"completed","conclusion":"failure","event":"release"}]');
      expect(r.exitCode, isNot(0), reason: r.output);
      expect(r.errored, isTrue);
      expect(r.output, contains(
          'never triggered (only non-push run(s) exist — the publish job fires on push-event tag runs only)'));
      expect(r.ghLog.where((l) => l.contains('run rerun')), isEmpty,
          reason: 'rerunning the release twin can never publish');
    });

    test('young tag with release-only runs visible -> grace skip, never alarms', () {
      // #1370 review: release-tag cuts the GitHub Release concurrently with
      // the tag push — the release twin registers while the push twin has
      // not. Within the grace window (60s-old tag < 900s) this is
      // release-in-flight, NOT «never triggered» (the #1189 false-alarm
      // class). Companion to the grace-expired alarm case above: both
      // branches pinned.
      final r = runVerify('young-release-twin',
          runsJson:
              '[{"databaseId":77,"status":"queued","conclusion":null,"event":"release"}]');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
      expect(r.output, isNot(contains('never triggered')));
    });

    test('release-only run registers on the spaced re-read -> still alarms (past grace)',
        () {
      final r = runVerify('release-twin-second-read',
          tagAge: const Duration(hours: 2),
          runsJson: '[]',
          secondReadJson:
              '[{"databaseId":77,"status":"completed","conclusion":"failure","event":"release"}]');
      expect(r.exitCode, isNot(0), reason: r.output);
      expect(r.errored, isTrue);
      expect(r.output, contains('only non-push run(s) exist'));
    });

    test('twin runs: recovery targets the PUSH twin, never the release twin',
        () {
      final r = runVerify('twin-runs',
          runsJson: '[{"databaseId":55,"status":"completed","conclusion":"failure","event":"release"},'
              '{"databaseId":4242,"status":"completed","conclusion":"failure","event":"push"}]',
          conclusion: 'failure',
          rerunToSuccess: true);
      expect(r.exitCode, 0, reason: r.output);
      expect(r.status, 'recovered');
      expect(r.outputs['run_url'],
          'https://github.com/OWNER/REPO/actions/runs/4242',
          reason: 'the push twin is the only OIDC-valid publisher');
      expect(
        r.ghLog.where((l) => l.contains('run rerun 4242') && l.contains('--failed')),
        hasLength(1),
      );
      expect(r.ghLog.where((l) => l.contains('run rerun 55')), isEmpty);
    });

    test('pending push run reaches terminal within the wait -> classified', () {
      final r = runVerify('terminal-flip',
          runsJson:
              '[{"databaseId":4242,"status":"queued","conclusion":null,"event":"push"}]',
          firstViewJson: '{"status":"queued","conclusion":null}',
          conclusion: 'failure',
          rerunToSuccess: true,
          extraEnv: const {'PUBDEV_MAX_POLLS': '4'});
      expect(r.exitCode, 0, reason: r.output);
      expect(r.status, 'recovered', reason: r.output);
      expect(
        r.ghLog.where((l) => l.contains('run rerun 4242') && l.contains('--failed')),
        hasLength(1),
      );
    });

    test('pending push run past the terminal-wait budget -> neutral skip, no error', () {
      // Acceptance 3: a simulated slow tag-ci (queued) must NOT fail the
      // verify with the «never triggered» message — the outcome is merely
      // unobserved.
      final r = runVerify('terminal-budget-lapse',
          runsJson:
              '[{"databaseId":4242,"status":"queued","conclusion":null,"event":"push"}]',
          extraEnv: const {'PUBDEV_MAX_POLLS': '2'});
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
      expect(r.output, contains('unobserved'));
      expect(r.output, isNot(contains('never triggered')));
    });

    test('tag appears during the appear-wait -> classified off its run', () {
      // The 2026-10-07 shape: the verify read no tag at 05:31:55; the tag
      // landed 05:35:13. The bounded wait must catch it instead of alarming.
      final r = runVerify('tag-appears-mid-wait',
          runsJson:
              '[{"databaseId":4242,"status":"queued","conclusion":null,"event":"push"}]',
          lsremoteFailFirst: true,
          extraEnv: const {'PUBDEV_MAX_POLLS': '2'});
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
      expect(r.output, contains('appeared after the wait'));
      expect(r.outputs['run_url'],
          'https://github.com/OWNER/REPO/actions/runs/4242');
    });

    test('bump present, tag absent past the appear-wait -> pending, not failed',
        () {
      final r = runVerify('appear-wait-lapse',
          tagPresent: false,
          bumpAge: const Duration(seconds: 90),
          extraEnv: const {'PUBDEV_MAX_POLLS': '2'});
      expect(r.exitCode, 0, reason: r.output);
      expect(r.inFlight, isTrue, reason: r.output);
      expect(r.errored, isFalse, reason: r.output);
      expect(r.output, contains('publish pending, not failed'));
    });
  });

  // ── unchanged paths pinned ────────────────────────────────────────────────
  group('verify — unchanged paths', () {
    test('up-to-date: pub.dev serves the pubspec version -> green no-op', () {
      final r = runVerify('up-to-date', publishedVersion: '0.1.497');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.status, 'up-to-date');
      expect(r.ghLog.where((l) => l.contains('run rerun')), isEmpty);
    });

    test('private package (publish_to: none) -> green no-op before any queries',
        () {
      final r = runVerify('private', publishToNone: true);
      expect(r.exitCode, 0, reason: r.output);
      expect(r.status, 'private');
      expect(r.ghLog, isEmpty, reason: 'nothing to verify on pub.dev');
    });

    test('E2: only the tag matching the CURRENT pubspec version is evaluated',
        () {
      final r = runVerify('e2-current-tag-only');
      expect(r.inFlight, isTrue, reason: r.output);
      final branches = r.ghLog
          .map((l) => RegExp(r'--branch (\S+)').firstMatch(l)?.group(1))
          .whereType<String>()
          .toSet();
      expect(branches, {'v0.1.497'},
          reason: 'stale older tags are out of scope (E2)');
    });
  });

  // ── AC1 — the report job files nothing for a release-in-flight leg ───────
  group('AC1 — report job files nothing for a release-in-flight leg', () {
    test('pubdev green + release-in-flight override -> no issue lifecycle action',
        () {
      final r = runReport('in-flight');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.ghLog.where((l) => l.contains('issue create')), isEmpty,
          reason: 'a release in flight is not a failure');
      expect(r.ghLog.where((l) => l.contains('issue comment')), isEmpty);
      expect(r.summary, contains('skipped: release in flight'));
      expect(r.output, isNot(contains('::error::')));
    });
  });

  // ── AC3 — the tag pins the bump commit, not moving main ─────────────────
  group('AC3 — tag_release.sh pins the bump commit', () {
    test(
      'simulated race: a commit landing on main between bump-push and '
      'tag-create must NOT appear in the tagged tree; tag commit == bump sha',
      () {
        final r = runTagRelease('race');
        expect(r.exitCode, 0, reason: r.output);
        // Fixture sanity: the checkout the script ran in really had drifted.
        expect(r.interloperSha, isNot(r.bumpSha));
        final tagged = r.tagCommit('0.1.496');
        expect(tagged, isNotNull, reason: 'the tag must be pushed');
        expect(tagged, r.bumpSha,
            reason:
                'the tag must pin the bump commit (9839a8b7d), not the '
                'interloper main had advanced to (065c2c67)');
        expect(r.fileInTag('0.1.496', 'pubspec.yaml'), contains('version: 0.1.496'));
        // The create command's --notes carries newlines, so the stub log
        // entry spans several lines — join the entry before asserting.
        final start = r.ghLog.indexWhere((l) => l.contains('release create'));
        final createText = r.ghLog.skip(start).take(10).join('\n');
        expect(createText, contains('--title v0.1.496'));
        expect(createText, contains('--latest'));
        expect(createText, contains('curated release note'),
            reason: 'notes must come from the pinned bump tree, not the drifted checkout');
      },
    );

    test('fallback: no BUMP_SHA (older wiring) — history search still pins the bump',
        () {
      final r = runTagRelease('fallback');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.tagCommit('0.1.496'), r.bumpSha,
          reason: 'the fallback must resolve the bump commit, never HEAD');
    });

    test('drifted BUMP_SHA (the incident mechanism) is rejected; the bump wins',
        () {
      // Whatever GitHub resolved github.sha to, a candidate that is not the
      // v0.1.496 bump must never be tagged — the script warns and falls
      // through to the history search.
      final r = runTagRelease('drifted', bumpShaEnv: 'INTERLOPER');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.output, contains('is not the v0.1.496 bump'));
      expect(r.tagCommit('0.1.496'), r.bumpSha);
    });

    test('unresolvable bump -> loud failure, NO tag pushed, no release create',
        () {
      final r = runTagRelease('unresolvable',
          interloper: false, seedSubject: 'chore: not a release bump');
      expect(r.exitCode, isNot(0), reason: 'refusing to tag a moving HEAD');
      expect(r.output, contains('refusing'));
      expect(r.tagCommit('0.1.496'), isNull);
      expect(r.ghLog.where((l) => l.contains('release create')), isEmpty);
    });

    test(
        'gh-1299 NG2 — a bump whose lockfile fails the enforce-lockfile smoke '
        'is NEVER tagged or published', () {
      // The v1.0.515 shape: the bump ships a pubspec.lock still pinning the
      // PRE-bump parent version. The smoke must refuse before git tag —
      // the tag is what fires every binaries/publish job.
      final r = runTagRelease('stale-lockfile', staleBumpLockfile: true);
      expect(r.exitCode, 1, reason:
          'the smoke must fail the release: ${r.output}');
      expect(
        r.output,
        contains('fails \'flutter pub get --enforce-lockfile\''),
      );
      expect(r.output, contains('refusing to tag/publish v0.1.496'));
      expect(r.tagCommit('0.1.496'), isNull,
          reason: 'no tag — nothing downstream may consume the broken bump');
      expect(r.ghLog.where((l) => l.contains('release create')), isEmpty,
          reason: 'no GitHub Release either');
    });

    test(
        'gh-1299 NG2 — a transient smoke failure (healthy pin, flutter itself '
        'broken) is NEVER tagged or published', () {
      // PR #1304 rework thread 2: exercises the `lockfileFails` knob (the
      // FA_FLUTTER_FAIL wiring makes the stub fail EVERY invocation), so the
      // refusal is driven by the smoke command itself dying — not by a stale
      // pin. Same never-tagged/never-published invariants as the
      // staleBumpLockfile case above.
      final r = runTagRelease('smoke-fails', lockfileFails: true);
      expect(r.exitCode, 1, reason:
          'the smoke must fail the release: ${r.output}');
      expect(
        r.output,
        contains('fails \'flutter pub get --enforce-lockfile\''),
      );
      expect(r.output, contains('refusing to tag/publish v0.1.496'));
      expect(r.tagCommit('0.1.496'), isNull,
          reason: 'no tag — nothing downstream may consume an unsmoked bump');
      expect(r.ghLog.where((l) => l.contains('release create')), isEmpty,
          reason: 'no GitHub Release either');
    });

    test(
        'gh-1299 NG2 — the smoke passes on a lockfile-refreshed bump and the '
        'tag still pins the bump sha', () {
      final r = runTagRelease('lockfile-ok');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.output, isNot(contains('refusing to tag/publish')));
      expect(r.tagCommit('0.1.496'), r.bumpSha);
      expect(r.fileInTag('0.1.496', 'flutter_app/pubspec.lock'),
          contains('version: "0.1.496"'),
          reason: 'the tagged tree ships the refreshed lockfile (AC2 shape)');
    });

    test('idempotent: an existing tag is a no-op before any sha resolution',
        () {
      final r = runTagRelease('idempotent', preExistingTag: true);
      expect(r.exitCode, 0, reason: r.output);
      expect(r.output, contains('already exists'));
      expect(r.ghLog.where((l) => l.contains('release create')), isEmpty);
      expect(r.tagCommit('0.1.496'), r.bumpSha);
    });
  });

  // ── wiring — the workflows must actually use the hardened paths ──────────
  group('wiring — workflows route through the hardened scripts', () {
    test('daily-publish.yml pubdev check calls verify_pubdev_release.sh', () {
      final daily = read('.github/workflows/daily-publish.yml');
      expect(daily, contains('scripts/verify_pubdev_release.sh'),
          reason: 'the check step must run the extracted, tested script');
      expect(daily, contains('Verify pub.dev serves the pubspec version'),
          reason: 'the step name stays (log-excerpt correlation keys on it)');
    });

    test('verify script default grace is 15 min (AC1 suggestion)', () {
      expect(read('scripts/verify_pubdev_release.sh'),
          contains('RELEASE_FLIGHT_GRACE_SECS:-900'));
    });

    test('ci.yml release-tag pins the tag to the push event bump sha', () {
      final ci = read('.github/workflows/ci.yml');
      expect(
        ci,
        contains('BUMP_SHA: \${{ github.event.head_commit.id || github.sha }}'),
        reason:
            'head_commit.id is frozen at push time — the checkout/github.sha '
            'can drift to a main that moved (the #1178 interloper capture)',
      );
    });

    test('#1368: publish gates on dart_ok and PUSH-event tags only', () {
      final ci = read('.github/workflows/ci.yml');
      expect(
          ci,
          contains(
              "!cancelled() && needs.quality-gate.outputs.dart_ok == 'true' &&"),
          reason: 'a red native/PTY leg must never block the Dart publish');
      expect(
          ci,
          contains("needs.integration.result == 'success' &&"),
          reason: 'the Provider smoke stays a hard publish gate (#551)');
      expect(
        ci,
        isNot(contains(
            "(github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')))")),
        reason:
            'the release arm is gone — pub.dev OIDC accepts push/workflow_'
            'dispatch events only; its attempts were the exit-65 failures',
      );
    });

    test('#1368: quality-gate exports dart_ok; platform legs cannot redden it',
        () {
      final ci = read('.github/workflows/ci.yml');
      expect(ci, contains('dart_ok: \${{ steps.gate.outputs.dart_ok }}'),
          reason: 'publish consumes the output');
      // The gate verdicts (review-thread fix on #1370): package legs feed
      // dart_blocker (dart_ok + aggregate), platform legs feed ONLY
      // platform_red (aggregate) — and dart_ok is exported BEFORE the fail
      // so it is always 'true'/'false', never ''.
      expect(ci, contains('platform_red=false'),
          reason: 'platform reds are tracked separately from dart_ok');
      expect(
          ci,
          contains(
              'if [ -n "\$dart_blocker" ]; then dart_ok=false; else dart_ok=true; fi'),
          reason: 'the export is explicit and precedes the aggregate fails');
      // The exclusion list inside the gate step: the full platform case
      // pattern, verbatim.
      expect(
          ci,
          contains('build-web|build-android|build-ios|build-macos|fa-aot-build|'
              'installer-verify|install-pin-gate|cube-kernel-live|'
              'cli-visual-settings|pty-integration-linux|pty-coverage-gate|'
              'pty-visual|flutter-app-lock-smoke)'),
          reason: 'every platform/native/PTY leg must be publish-exempt — '
              'flutter-app-lock-smoke included (#1267 N2: a red lockfile '
              'smoke release build blocks the merge via the aggregate, '
              'never the publish)');
    });

    test('#1368: the Provider smoke runs off dart_ok, not the aggregate result',
        () {
      final ci = read('.github/workflows/ci.yml');
      expect(
          ci,
          contains(
              "!cancelled() && needs.quality-gate.outputs.dart_ok != 'false' &&"),
          reason:
              'a platform-only red must not transitively skip the smoke and '
              'with it the publish');
    });

    test('#1368: report renders release-in-flight as a skip, never ✅', () {
      final report = read('scripts/daily_publish_report.sh');
      expect(report, contains('release-in-flight'));
      expect(report, contains('skipped: release in flight'));
      expect(report, contains('== "skipped:"*'),
          reason: 'the neutral-skip override must downgrade ✅ to ⏭️ and '
              'keep the leg issue open');
      expect(report, contains('outcome unobserved'));
    });

    test('report script renders the release-in-flight override neutrally', () {
      final report = read('scripts/daily_publish_report.sh');
      expect(report, contains('release-in-flight'));
      expect(report, contains('skipped: release in flight'));
    });

    test('plan job change detection runs the extracted, tested script', () {
      final daily = read('.github/workflows/daily-publish.yml');
      expect(daily, contains('scripts/daily_plan.sh'),
          reason:
              'the plan gate (baseline + gh-1192 release-unresolved re-arm) '
              'must be the shell-harness tested script, not inline drift');
      expect(daily, contains('Detect main movement and derive versions'),
          reason: 'the step name stays (log-excerpt correlation keys on it)');
    });
  });

  // ── review thread 1 — the release-unresolved re-arm ──────────────────────
  // A release-in-flight pubdev leg exits 0, so that daily goes GREEN and
  // becomes the plan job's new baseline AT THE BUMP'S sha. If main then
  // stays quiet, every later daily would skip all legs — AC1's «the next
  // scheduled daily re-verifies» and the failed-run `rerun --failed`
  // recovery would stall until an unrelated push. The gate must therefore
  // force the legs while main's pubspec version is not served by pub.dev.
  group('plan gate — re-arms the daily while a release is unresolved', () {
    test('main moved since the last green daily -> legs run, pub.dev not consulted',
        () {
      final r = runPlan('main-moved', lastGreen: 'older');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.changed, isTrue, reason: r.output);
      expect(r.curlLog, isEmpty,
          reason: 'the baseline decision already forces the legs');
    });

    test('main quiet + pub.dev serves the pubspec version -> all legs skip (unchanged)',
        () {
      final r = runPlan('quiet-served', lastGreen: 'head');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.changed, isFalse, reason: r.output);
      expect(r.outputs['latest_tag'], 'v0.1.496');
      expect(r.outputs['next_tag'], 'v0.1.497');
      expect(r.outputs['pubspec_version'], '0.1.497');
    });

    test(
        'main quiet + pub.dev BEHIND (release-in-flight green became the '
        'baseline) -> re-armed: changed=true, next daily re-verifies', () {
      final r = runPlan('quiet-release-unresolved',
          lastGreen: 'head', servedVersion: '0.1.496');
      expect(r.exitCode, 0, reason: r.output);
      expect(r.changed, isTrue,
          reason: 'AC1 re-verification must not stall on a quiet main');
      expect(r.output, contains('release unresolved'));
      expect(r.outputs['next_tag'], 'v0.1.497',
          reason: 'version derivation still runs after the re-arm');
    });

    test('pub.dev read fails -> fail OPEN: the baseline skip stands, exit 0', () {
      final r = runPlan('api-down', lastGreen: 'head', pubdevApiDown: true);
      expect(r.exitCode, 0, reason: r.output);
      expect(r.changed, isFalse,
          reason: 'an API outage must not force daily legs by itself');
    });

    test('FORCE=true forces the legs without consulting pub.dev', () {
      final r = runPlan('forced', lastGreen: 'head', force: true);
      expect(r.exitCode, 0, reason: r.output);
      expect(r.changed, isTrue, reason: r.output);
      expect(r.curlLog, isEmpty, reason: 'FORCE short-circuits before the re-arm');
    });

    test('no green all-legs daily recorded -> legs run (first-run path unchanged)',
        () {
      final r = runPlan('first-run', lastGreen: null);
      expect(r.exitCode, 0, reason: r.output);
      expect(r.changed, isTrue, reason: r.output);
      expect(r.curlLog, isEmpty);
    });
  });

  // ── review thread 3 — the fixture must not swallow unknown gh calls ──────
  group('fixture hygiene — the gh stub fails loudly on unexpected commands', () {
    late Directory dir;
    late StubEnv stub;
    setUp(() {
      dir = Directory(
              '${_fixtureRoot.path}/stub-strict-${DateTime.now().microsecondsSinceEpoch}')
        ..createSync(recursive: true);
      stub = _installStubs(dir.path);
    });

    Map<String, String> stubEnv() => {
          'GH_STUB_DIR': dir.path,
          'GH_LOG_FILE': '${dir.path}/gh.log',
        };

    test('an unknown subcommand exits non-zero with a loud stderr', () {
      final r = Process.runSync('${stub.bin}/gh', ['api', 'repos/OWNER/REPO'],
          environment: stubEnv());
      expect(r.exitCode, isNot(0), reason: 'script drift must turn red');
      expect(r.stderr, contains('unexpected gh invocation'));
    });

    test('gh release create stays a quiet success (tag_release.sh path)', () {
      final r = Process.runSync(
          '${stub.bin}/gh',
          [
            'release',
            'create',
            'v0.1.496',
            '--title',
            'v0.1.496',
            '--notes',
            'notes',
            '--latest',
            '--repo',
            'OWNER/REPO',
          ],
          environment: stubEnv());
      expect(r.exitCode, 0, reason: r.stderr);
    });

    test('the known subcommands still answer (no over-tightening)', () {
      File('${dir.path}/runs-v1.json')
          .writeAsStringSync('[{"databaseId":7,"status":"queued"}]');
      final list = Process.runSync('${stub.bin}/gh',
          ['run', 'list', '--branch', 'v1', '--jq', '.[0].databaseId'],
          environment: stubEnv());
      expect(list.exitCode, 0, reason: list.stderr);
      expect(list.stdout.trim(), '7');
      final label = Process.runSync(
          '${stub.bin}/gh', ['label', 'create', 'daily-publish'],
          environment: stubEnv());
      expect(label.exitCode, 0, reason: label.stderr);
    });
  });
}
