/// Slim marketing frame for the App Store screenshots generated by
/// `store_screenshots_test.dart`.
///
/// The frame composites a real app screen into a full-bleed marketing
/// canvas: a dark gradient in the app palette with two soft accent glows,
/// a localized headline + subtitle on top, and the app screen below,
/// clipped into a rounded "device" card with a border and a soft shadow.
/// The output PNGs are committed under `test/goldens/store/<lang>/<device>/`
/// and uploaded to App Store Connect by the `app_store` fastlane lanes, so
/// the localized copy lives here (en + ru) — never in the upload pipeline.
library;

import 'package:fa/ui/app_theme.dart';
import 'package:flutter/material.dart';

/// Localized marketing copy per store screenshot: screen name → language →
/// (headline, subtitle). English is the fallback for missing languages.
///
/// The five frames tell one story ("your own apps, built by chat"): the
/// user asks Fa to build a personal weather app with a dashboard widget,
/// the app appears on the home-screen dashboard as a live widget tile, a
/// follow-up tweak happens without leaving the app, a media frame shows
/// the generation tools, and the settings frame closes with the provider
/// story.
const kStoreCopy = <String, Map<String, (String, String)>>{
  'store_chat': {
    'en': (
      'Your own apps, built by chat',
      'The first mobile agent harness — describe an app and Fa builds it',
    ),
    'ru': (
      'Свои приложения — прямо из чата',
      'Первый мобильный ИИ-агент: опишите приложение, и Fa его соберёт',
    ),
  },
  'store_apps': {
    'en': (
      'A dashboard that is truly yours',
      'Live widgets from the apps Fa built for you, right on the home screen',
    ),
    'ru': (
      'Дашборд, который действительно ваш',
      'Живые виджеты ваших приложений — на домашнем экране',
    ),
  },
  'store_inapp': {
    'en': (
      'Fa lives inside every app',
      '“Add a weekly forecast” — chat and tweaks without leaving the app',
    ),
    'ru': (
      'Fa живёт в каждом приложении',
      '«Добавь прогноз на неделю» — правки, не выходя из приложения',
    ),
  },
  'store_media': {
    'en': (
      'It draws, speaks and plays',
      'Wallpapers, voice summaries and clips — generated inline in the chat',
    ),
    'ru': (
      'Рисует, говорит и показывает',
      'Обои, голосовые сводки и ролики — прямо в диалоге',
    ),
  },
  'store_providers': {
    'en': (
      'Any provider — keys stay in the Keychain',
      'OpenRouter, local Ollama or your own endpoint, cloud or on-device',
    ),
    'ru': (
      'Любой провайдер — ключи в Keychain',
      'OpenRouter, локальный Ollama или свой сервер, облако или on-device',
    ),
  },
};

/// Full-canvas marketing frame: gradient background, localized text block
/// on top, and [child] (a real app screen) in a rounded device card below.
class StoreFrame extends StatelessWidget {
  const StoreFrame({
    required this.screen,
    required this.lang,
    required this.child,
    super.key,
  });

  /// Key into [kStoreCopy] (e.g. `store_chat`).
  final String screen;

  /// Language code for the copy (`en`, `ru`); English is the fallback.
  final String lang;

  /// The real app screen filling the device card.
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final copy = kStoreCopy[screen];
    final localized = copy?[lang] ?? copy?['en'] ?? ('', '');
    return LayoutBuilder(
      builder: (context, constraints) {
        final w = constraints.maxWidth;
        final h = constraints.maxHeight;
        final isLandscape = w > h;

        final textAreaH = h * (isLandscape ? 0.17 : 0.22);
        final titleSize = h * (isLandscape ? 0.052 : 0.032);
        final subtitleSize = titleSize * 0.55;
        final sidePad = w * (isLandscape ? 0.07 : 0.055);

        final textBlock = SizedBox(
          width: w,
          height: textAreaH,
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: sidePad),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  localized.$1,
                  style: TextStyle(
                    fontFamily: 'Inter',
                    fontSize: titleSize,
                    fontWeight: FontWeight.w700,
                    color: FahPalette.text,
                    height: 1.1,
                  ),
                  textAlign: TextAlign.center,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
                SizedBox(height: h * 0.012),
                Text(
                  localized.$2,
                  style: TextStyle(
                    fontFamily: 'Inter',
                    fontSize: subtitleSize,
                    fontWeight: FontWeight.w400,
                    color: FahPalette.dim,
                    height: 1.3,
                  ),
                  textAlign: TextAlign.center,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
        );

        final deviceCard = Expanded(
          child: Padding(
            padding: EdgeInsets.fromLTRB(
              sidePad,
              0,
              sidePad,
              h * (isLandscape ? 0.05 : 0.035),
            ),
            child: Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(w * 0.04),
                border: Border.all(color: FahPalette.borderBright),
                boxShadow: const [
                  BoxShadow(
                    color: Color(0x59818CF8),
                    blurRadius: 60,
                    spreadRadius: -12,
                  ),
                ],
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(w * 0.04),
                child: child,
              ),
            ),
          ),
        );

        return Material(
          color: FahPalette.bg,
          child: Stack(
            fit: StackFit.expand,
            children: [
              const Positioned.fill(
                child: DecoratedBox(
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                      colors: [Color(0xFF101A2E), FahPalette.bg],
                    ),
                  ),
                ),
              ),
              Positioned(
                right: -w * 0.2,
                top: -h * 0.15,
                child: _Glow(color: FahPalette.indigo, size: w * 0.6),
              ),
              Positioned(
                left: -w * 0.25,
                bottom: -h * 0.2,
                child: _Glow(color: FahPalette.teal, size: w * 0.55),
              ),
              Column(children: [textBlock, deviceCard]),
            ],
          ),
        );
      },
    );
  }
}

/// A soft radial accent glow behind the content.
class _Glow extends StatelessWidget {
  const _Glow({required this.color, required this.size});

  final Color color;
  final double size;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: RadialGradient(
          colors: [color.withValues(alpha: 0.16), color.withValues(alpha: 0)],
        ),
      ),
    );
  }
}
