/// Slim marketing frame for the App Store screenshots generated by
/// `store_screenshots_test.dart`.
///
/// The frame composites a real app screen into a full-bleed marketing
/// canvas: a dark gradient in the app palette with two soft accent glows,
/// a localized headline + subtitle on top, and the app screen below,
/// clipped into a rounded "device" card with a border and a soft shadow.
/// The output PNGs are committed under `test/goldens/store/<lang>/<device>/`
/// and uploaded to App Store Connect by the `app_store` fastlane lanes, so
/// the localized copy lives here (en + ru) — never in the upload pipeline.
library;

import 'package:fa/ui/app_theme.dart';
import 'package:flutter/material.dart';

/// Localized marketing copy per store screenshot: screen name → language →
/// (headline, subtitle). English is the fallback for missing languages.
const kStoreCopy = <String, Map<String, (String, String)>>{
  'store_chat': {
    'en': (
      'Your personal AI agent',
      'Ask anything — Fa thinks, calls tools, and shows every step',
    ),
    'ru': (
      'Ваш личный ИИ-агент',
      'Спросите что угодно — Fa рассуждает и показывает каждый шаг',
    ),
  },
  'store_sidebar': {
    'en': (
      'Apps and sessions, side by side',
      'Mini-apps the agent builds for you, next to every conversation',
    ),
    'ru': (
      'Приложения и сессии рядом',
      'Мини-приложения от агента — рядом с каждым диалогом',
    ),
  },
  'store_js_app': {
    'en': (
      'Mini-apps built on demand',
      'Fa writes real apps — calculators, maps, calendars — right inside the chat',
    ),
    'ru': (
      'Мини-приложения по запросу',
      'Fa пишет настоящие приложения прямо в чате',
    ),
  },
  'store_providers': {
    'en': (
      'Any provider, your keys',
      'OpenAI-compatible endpoints and on-device models — keys stay in the Keychain',
    ),
    'ru': (
      'Любой провайдер, ваши ключи',
      'OpenAI-совместимые API и локальные модели, ключи в Keychain',
    ),
  },
  'store_media': {
    'en': (
      'Images, speech and music',
      'Dedicated media models per slot — configured once, stored securely',
    ),
    'ru': (
      'Изображения, речь и музыка',
      'Медиа-модели для каждого слота — настройка раз и навсегда',
    ),
  },
};

/// Full-canvas marketing frame: gradient background, localized text block
/// on top, and [child] (a real app screen) in a rounded device card below.
class StoreFrame extends StatelessWidget {
  const StoreFrame({
    required this.screen,
    required this.lang,
    required this.child,
    super.key,
  });

  /// Key into [kStoreCopy] (e.g. `store_chat`).
  final String screen;

  /// Language code for the copy (`en`, `ru`); English is the fallback.
  final String lang;

  /// The real app screen filling the device card.
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final copy = kStoreCopy[screen];
    final localized = copy?[lang] ?? copy?['en'] ?? ('', '');
    return LayoutBuilder(
      builder: (context, constraints) {
        final w = constraints.maxWidth;
        final h = constraints.maxHeight;
        final isLandscape = w > h;

        final textAreaH = h * (isLandscape ? 0.17 : 0.22);
        final titleSize = h * (isLandscape ? 0.052 : 0.032);
        final subtitleSize = titleSize * 0.55;
        final sidePad = w * (isLandscape ? 0.07 : 0.055);

        final textBlock = SizedBox(
          width: w,
          height: textAreaH,
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: sidePad),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  localized.$1,
                  style: TextStyle(
                    fontFamily: 'Inter',
                    fontSize: titleSize,
                    fontWeight: FontWeight.w700,
                    color: FahPalette.text,
                    height: 1.1,
                  ),
                  textAlign: TextAlign.center,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
                SizedBox(height: h * 0.012),
                Text(
                  localized.$2,
                  style: TextStyle(
                    fontFamily: 'Inter',
                    fontSize: subtitleSize,
                    fontWeight: FontWeight.w400,
                    color: FahPalette.dim,
                    height: 1.3,
                  ),
                  textAlign: TextAlign.center,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
        );

        final deviceCard = Expanded(
          child: Padding(
            padding: EdgeInsets.fromLTRB(
              sidePad,
              0,
              sidePad,
              h * (isLandscape ? 0.05 : 0.035),
            ),
            child: Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(w * 0.04),
                border: Border.all(color: FahPalette.borderBright),
                boxShadow: const [
                  BoxShadow(
                    color: Color(0x59818CF8),
                    blurRadius: 60,
                    spreadRadius: -12,
                  ),
                ],
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(w * 0.04),
                child: child,
              ),
            ),
          ),
        );

        return Material(
          color: FahPalette.bg,
          child: Stack(
            fit: StackFit.expand,
            children: [
              const Positioned.fill(
                child: DecoratedBox(
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                      colors: [Color(0xFF101A2E), FahPalette.bg],
                    ),
                  ),
                ),
              ),
              Positioned(
                right: -w * 0.2,
                top: -h * 0.15,
                child: _Glow(color: FahPalette.indigo, size: w * 0.6),
              ),
              Positioned(
                left: -w * 0.25,
                bottom: -h * 0.2,
                child: _Glow(color: FahPalette.teal, size: w * 0.55),
              ),
              Column(children: [textBlock, deviceCard]),
            ],
          ),
        );
      },
    );
  }
}

/// A soft radial accent glow behind the content.
class _Glow extends StatelessWidget {
  const _Glow({required this.color, required this.size});

  final Color color;
  final double size;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: RadialGradient(
          colors: [color.withValues(alpha: 0.16), color.withValues(alpha: 0)],
        ),
      ),
    );
  }
}
