#!/usr/bin/env bash
# install.sh — non-interactive one-line installer for the Fa CLI
#              (flutter_agent_harness). Works when piped:
#                curl -fsSL "https://fa1.dev/install.sh" | sh
#
# What it does:
#   1. Detects OS and architecture.
#   2. Downloads the matching Fa binary from the latest GitHub Release.
#   3. Installs it to a directory on your PATH.
#   4. Prints a concise setup recipe and exits.
#
# Fallback: if the binary is unavailable for this platform, the script falls
# back to `dart pub global activate`, which requires the Dart SDK.
#
# For interactive configuration (provider, model, API key), run:
#   curl -fsSL "https://fa1.dev/setup.sh" | sh
#
# ═══════════════════════════════════════════════════════════════════════════
#  DO NOT EDIT THIS FILE BY HAND. It is generated from site/install-config.yaml
#  by `dart run scripts/gen_installers.dart`.
# ═══════════════════════════════════════════════════════════════════════════

set -eu  # no pipefail: dash (Ubuntu sh) lacks it

REPO="IstiN/flutter_agent_harness"
BINARY="fa"

# ── Output helpers ───────────────────────────────────────────────────────────
say() {
  printf '%s\n' "$*"
}

info() {
  printf '\033[1;34m→\033[0m %s\n' "$*"
}

ok() {
  printf '\033[1;32m✔\033[0m %s\n' "$*"
}

warn() {
  printf '\033[1;33m!\033[0m %s\n' "$*" >&2
}

err() {
  printf '\033[1;31m✘\033[0m %s\n' "$*" >&2
}

# ── Banner ───────────────────────────────────────────────────────────────────
say ""
say "  ███████╗ █████╗       ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗"
say "  ██╔════╝██╔══██╗      ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║"
say "  █████╗  ███████║█████╗   ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║"
say "  ██╔══╝  ██╔══██║╚════╝   ██║   ╚════╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║"
say "  ██║     ██║  ██║         ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗"
say "  ╚═╝     ╚═╝  ╚═╝         ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝"
say ""
say "  Fa installer — flutter_agent_harness CLI"
say ""


# ── 0. Platform check ────────────────────────────────────────────────────────
# This script is for Unix-like shells. Native Windows users should use the
# PowerShell installer instead. Git Bash / MSYS / Cygwin can run this script,
# but the PowerShell installer is the recommended Windows path because it
# configures the user PATH and environment variables correctly.
case "${OSTYPE:-}" in
  msys*|cygwin*|mingw*)
    warn "you appear to be running in a Bash emulation layer on Windows."
    say ""
    say "  For the best Windows experience, use the PowerShell installer:"
    say ""
    say "    irm https://fa1.dev/install.ps1 | iex"
    say ""
    exit 0
    ;;
esac

# ── 1. Detect OS/arch ────────────────────────────────────────────────────────
os=""
arch=""
case "$(uname -s)" in
  Linux*)     os=linux ;;
  Darwin*)    os=macos ;;
  *)
    err "unsupported OS: $(uname -s)"
    exit 1
    ;;
esac

case "$(uname -m)" in
  x86_64|amd64)  arch=x64 ;;
  arm64|aarch64) arch=arm64 ;;
  armv7l)        arch=arm ;;
  *)
    err "unsupported architecture: $(uname -m)"
    exit 1
    ;;
esac

asset="fa-${os}-${arch}.tar.gz"

# ── 2. Resolve install directory ─────────────────────────────────────────────
# Prefer a directory already on PATH, falling back to ~/.local/bin.
# (POSIX-only syntax below: Ubuntu's /bin/sh is dash, no arrays/[[]]/pipefail.)
install_dir="${FA_INSTALL_DIR:-$HOME/.local/bin}"
case ":${PATH}:" in
  *":$install_dir:"*) ;;
  *":$HOME/.local/bin:"*) install_dir="$HOME/.local/bin" ;;
  *":$HOME/bin:"*) install_dir="$HOME/bin" ;;
esac

mkdir -p "$install_dir"
target="$install_dir/$BINARY"

# ── 3. Resolve download URL ──────────────────────────────────────────────────
download_url="https://github.com/$REPO/releases/latest/download/$asset"

# ── 4. Helper: extract binary from macOS .app bundle .zip ────────────────────
_extract_macos_zip() {
  local zip="$1" out="$2"
  local tmpdir
  tmpdir="$(mktemp -d 2>/dev/null || mktemp -d -t fa-install)"
  unzip -qo "$zip" -d "$tmpdir" 2>/dev/null || return 1
  local binary="$tmpdir/Fa.app/Contents/MacOS/Fa"
  if [ -f "$binary" ]; then
    cp "$binary" "$out"
    chmod +x "$out"
    rm -rf "$tmpdir" "$zip"
    return 0
  fi
  rm -rf "$tmpdir" "$zip"
  return 1
}

# ── 5. Install bundle (or fall back to .zip, then Dart) ──────────────────────
info "Downloading Fa for ${os}-${arch}..."
dl_ok=false
tmp_archive="$(mktemp 2>/dev/null || mktemp -t fa-archive)"
if command -v curl >/dev/null 2>&1; then
  if curl -fSL --progress-bar "$download_url" -o "$tmp_archive" 2>/dev/null; then
    dl_ok=true
  fi
else
  if wget --show-progress -qO "$tmp_archive" "$download_url" 2>/dev/null; then
    dl_ok=true
  fi
fi

if [ "$dl_ok" = true ]; then
  # dart build cli produces a bundle/ dir: bundle/bin/fa + bundle/lib/*.dylib
  # Extract the bundle, copy bin/ and lib/ into the install dir.
  tmp_extract="$(mktemp -d 2>/dev/null || mktemp -d -t fa-extract)"
  if tar -xzf "$tmp_archive" -C "$tmp_extract" 2>/dev/null; then
    mkdir -p "$install_dir/lib"
    cp "$tmp_extract/bundle/bin/fa" "$target"
    chmod +x "$target"
    if [ -d "$tmp_extract/bundle/lib" ]; then
      cp -r "$tmp_extract/bundle/lib/"* "$install_dir/lib/" 2>/dev/null || true
    fi
    rm -rf "$tmp_extract" "$tmp_archive"
    ok "Installed $target"
  else
    rm -rf "$tmp_extract" "$tmp_archive"
    dl_ok=false
  fi
fi

# macOS fallback: try the sandboxed .zip and extract the binary from the app bundle.
if [ "$dl_ok" = false ] && [ "$os" = "macos" ]; then
  zip_asset="fa-${os}-${arch}-mac.zip"
  zip_url="https://github.com/$REPO/releases/latest/download/$zip_asset"
  info "archive not found — trying $zip_asset…"
  zip_tmp="$(mktemp 2>/dev/null || mktemp -t fa-zip)"
  if command -v curl >/dev/null 2>&1; then
    curl -fSL --progress-bar "$zip_url" -o "$zip_tmp" 2>/dev/null
  else
    wget --show-progress -qO "$zip_tmp" "$zip_url" 2>/dev/null
  fi
  if [ -f "$zip_tmp" ] && [ -s "$zip_tmp" ]; then
    if _extract_macos_zip "$zip_tmp" "$target"; then
      dl_ok=true
    fi
  fi
fi

if [ "$dl_ok" = true ]; then
  ok "Installed $target"
else
  warn "No prebuilt binary found for ${os}-${arch} (or download failed). Falling back to Dart pub global activate."
  FALLBACK=true
fi

if [ "${FALLBACK:-}" = true ]; then
  if ! command -v dart >/dev/null 2>&1; then
    err "the Dart SDK ('dart') is not on your PATH, and no prebuilt binary is available for ${os}-${arch}."
    say ""
    say "  Install Flutter (includes Dart) from:"
    say ""
    say "    https://docs.flutter.dev/get-started/install"
    say ""
    exit 1
  fi
  PACKAGE="flutter_agent_harness"
  PUB_CACHE_BIN="${PUB_CACHE_BIN:-$HOME/.pub-cache/bin}"
  info "Activating $PACKAGE from pub.dev..."
  dart pub global activate "$PACKAGE"
  install_dir="$PUB_CACHE_BIN"
  target="$install_dir/$BINARY"
fi

# ── 5. Ensure install directory is on PATH ───────────────────────────────────
if command -v fa >/dev/null 2>&1 || command -v fah >/dev/null 2>&1; then
  ok "'fa' is on PATH ($(command -v fa 2>/dev/null || command -v fah))."
else
  warn "'fa' is not on PATH yet. The executable lives in $install_dir"
  say ""

  shell_rc=""
  case "${SHELL:-}" in
    */zsh)  shell_rc="$HOME/.zshrc" ;;
    */bash) shell_rc="$HOME/.bashrc" ;;
    */fish) shell_rc="$HOME/.config/fish/config.fish" ;;
  esac

  if [ -n "$shell_rc" ]; then
    mkdir -p "$(dirname "$shell_rc")"
    if [ -f "$shell_rc" ] && grep -qF "$install_dir" "$shell_rc" 2>/dev/null; then
      ok "$install_dir is already referenced in $shell_rc"
    else
      printf '\n# Fa CLI PATH\nexport PATH="$PATH:%s"\n' "$install_dir" >> "$shell_rc"
      ok "Added $install_dir to $shell_rc"
    fi
    say ""
    warn "Open a new terminal window/tab, or run this in the current shell:"
    say ""
    printf '    source %s\n' "$shell_rc"
    say ""
    warn "To use 'fa' right now without reloading, run:"
    say ""
    printf '    export PATH="$PATH:%s"\n' "$install_dir"
    say ""
  else
    warn "Add this to your shell startup file (and open a new terminal):"
    say ""
    printf '    export PATH="$PATH:%s"\n' "$install_dir"
    say ""
  fi
fi

# ── 6. Done ──────────────────────────────────────────────────────────────────
say ""
ok "Installation complete."
say ""
say "  Configure a provider and API key interactively:"
say ""
say "    curl -fsSL https://fa1.dev/setup.sh | sh"
say ""
say "  Or set an environment variable manually:"
say ""
say "    export OPENROUTER_API_KEY=<your-key>   # or ANTHROPIC_API_KEY / GOOGLE_API_KEY / OPENAI_API_KEY"
say ""
say "  Then start the agent:"
say ""
say "    fa"
say ""
say "  Or run a single headless task:"
say ""
say "    fa \"summarize CHANGELOG.md\""
say ""
say "  (the legacy command 'fah' also works)"
say ""
say "  Docs:    https://github.com/IstiN/flutter_agent_harness"
say "  Package: https://pub.dev/packages/flutter_agent_harness"
say ""

