# install.ps1 — non-interactive one-line installer for the Fa CLI on Windows.
#                 Works when piped from PowerShell:
#                   irm https://fa1.dev/install.ps1 | iex
#
# From Windows Command Prompt (cmd.exe) use the wrapper instead:
#   curl -fsSL https://fa1.dev/install.bat -o install.bat && install.bat
#
# What it does:
#   1. Detects OS architecture.
#   2. Downloads the matching Fa binary from the latest GitHub Release.
#   3. Installs it to a directory on the user PATH.
#   4. Prints a concise setup recipe and exits.
#
# Fallback: if the binary is unavailable for this platform, the script falls
# back to `dart pub global activate`, which requires the Dart SDK.
#
# For interactive configuration (provider, model, API key), run:
#   irm https://fa1.dev/setup.ps1 | iex
#
# ═══════════════════════════════════════════════════════════════════════════
#  DO NOT EDIT THIS FILE BY HAND. It is generated from site/install-config.yaml
#  by `dart run scripts/gen_installers.dart`.
# ═══════════════════════════════════════════════════════════════════════════

#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$Repo = "IstiN/flutter_agent_harness"
$BinaryName = "fa"

# ── Output helpers ───────────────────────────────────────────────────────────
function Write-Info($msg) { Write-Host "→ $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "✔ $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "! $msg" -ForegroundColor Yellow }
function Write-Err($msg) { Write-Host "✘ $msg" -ForegroundColor Red }

# ── Banner ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ███████╗ █████╗       ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗"
Write-Host "  ██╔════╝██╔══██╗      ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║"
Write-Host "  █████╗  ███████║█████╗   ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║"
Write-Host "  ██╔══╝  ██╔══██║╚════╝   ██║   ╚════╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║"
Write-Host "  ██║     ██║  ██║         ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗"
Write-Host "  ╚═╝     ╚═╝  ╚═╝         ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝"
Write-Host ""
Write-Host "  Fa installer — flutter_agent_harness CLI (Windows)"
Write-Host ""

# ── 1. Detect platform ───────────────────────────────────────────────────────
$arch = if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "ia32" }
# ARM64 Windows detection via processor architecture.
if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64" -or $env:PROCESSOR_ARCHITEW6432 -eq "ARM64") {
    $arch = "arm64"
}
$assetName = "fa-windows-$arch.exe"

# ── 2. Resolve install directory ─────────────────────────────────────────────
$installDir = Join-Path $env:LOCALAPPDATA "Fa"
$oldBin = Join-Path $installDir "bin"
# Prefer a directory that is already on PATH.
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$pathParts = $userPath -split ';' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
$existingDir = $pathParts | Where-Object { $_ -like "*\Fa\bin" -or $_ -like "*\.local\bin" } | Select-Object -First 1
if ($existingDir) {
    $installDir = Split-Path $existingDir
} elseif ($oldBin -in $pathParts) {
    $installDir = $oldBin
}

if (-not (Test-Path $installDir)) {
    New-Item -ItemType Directory -Force -Path $installDir | Out-Null
}
$target = Join-Path $installDir "$BinaryName.exe"

# ── 3. Resolve download URL ──────────────────────────────────────────────────
$downloadUrl = "https://github.com/$Repo/releases/latest/download/$assetName"

# ── 4. Install binary (or fall back to Dart) ─────────────────────────────────
Write-Info "Downloading Fa for windows-$arch..."
try {
    $progressPreference = 'silentlyContinue'
    Invoke-WebRequest -Uri $downloadUrl -OutFile $target -UseBasicParsing -MaximumRedirection 5
    $progressPreference = 'Continue'
    Write-Ok "Downloaded $target"
} catch {
    # A 404 usually means no binary was published for this platform yet.
    $status = $_.Exception.Response.StatusCode.value__
    if ($status -eq 404) {
        Write-Warn "No prebuilt binary found for windows-$arch. Falling back to Dart pub global activate."
    } else {
        Write-Warn "Binary download failed (HTTP $status). Falling back to Dart pub global activate."
    }
    $dart = Get-Command dart -ErrorAction SilentlyContinue
    if (-not $dart) {
        Write-Err "the Dart SDK ('dart') is not on your PATH, and no prebuilt binary is available for windows-$arch."
        Write-Host ""
        Write-Host "  Install Flutter (includes Dart) from:"
        Write-Host ""
        Write-Host "    https://docs.flutter.dev/get-started/install"
        Write-Host ""
        exit 1
    }
    Write-Info "Activating flutter_agent_harness from pub.dev..."
    & dart pub global activate flutter_agent_harness
    $pubCacheBin = if ($env:PUB_CACHE_BIN) { $env:PUB_CACHE_BIN } else { Join-Path $env:LOCALAPPDATA "Pub\Cache\bin" }
    if (-not (Test-Path $pubCacheBin)) { $pubCacheBin = Join-Path $env:APPDATA "Pub\Cache\bin" }
    $installDir = $pubCacheBin
    $target = Join-Path $installDir "$BinaryName.bat"
}

# ── 5. Ensure install directory is on the user PATH ──────────────────────────
if ($installDir -notin $pathParts) {
    Write-Info "Adding $installDir to your user PATH"
    $newPath = ($pathParts + $installDir) -join ';'
    [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
}

# Refresh PATH in the current session.
$env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [Environment]::GetEnvironmentVariable("Path", "User")
$processPaths = $env:Path -split ';' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
if ($installDir -notin $processPaths) {
    $env:Path = ($processPaths + $installDir) -join ';'
}

$faCmd = Get-Command fa -ErrorAction SilentlyContinue
if (-not $faCmd) { $faCmd = Get-Command fah -ErrorAction SilentlyContinue }
if ($faCmd) {
    Write-Ok "'fa' is on PATH ($($faCmd.Source))."
} else {
    Write-Warn "'fa' is not on PATH yet. The executable lives in $installDir"
    Write-Host ""
    Write-Warn "Open a new PowerShell window, or run this in the current one:"
    Write-Host ""
    Write-Host "    `$env:Path = `$env:Path + ';$installDir'"
    Write-Host ""
}

# ── 6. Done ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Ok "Installation complete."
Write-Host ""
Write-Host "  Configure a provider and API key interactively:"
Write-Host ""
Write-Host "    irm https://fa1.dev/setup.ps1 | iex"
Write-Host ""
Write-Host "  Or set an environment variable manually:"
Write-Host ""
Write-Host "    `$env:OPENROUTER_API_KEY = '<your-key>'   # or ANTHROPIC_API_KEY / GOOGLE_API_KEY / OPENAI_API_KEY"
Write-Host ""
Write-Host "  Then start the agent:"
Write-Host ""
Write-Host "    fa"
Write-Host ""
Write-Host "  Or run a single headless task:"
Write-Host ""
Write-Host "    fa `"summarize CHANGELOG.md`""
Write-Host ""
Write-Host "  (the legacy command 'fah' also works)"
Write-Host ""
Write-Host "  Docs:    https://github.com/IstiN/flutter_agent_harness"
Write-Host "  Package: https://pub.dev/packages/flutter_agent_harness"
Write-Host ""
