@echo off
:: install.bat — one-line installer wrapper for the Fa CLI on Windows cmd.exe.
::
:: This file is for users running from Command Prompt (cmd.exe). It delegates
:: to the PowerShell installer, which does the actual work:
::   1. Detects the Windows architecture.
::   2. Downloads the matching Fa binary from the latest GitHub Release.
::   3. Installs it to a directory on the user PATH.
::   4. Falls back to `dart pub global activate` if no binary is available.
::
:: Run from cmd:
::   curl -fsSL "https://fa1.dev/install.bat" -o install.bat && install.bat
::
:: Or directly from PowerShell:
::   irm https://fa1.dev/install.ps1 | iex
::
:: ═══════════════════════════════════════════════════════════════════════════
::  DO NOT EDIT THIS FILE BY HAND. It is generated from site/install-config.yaml
::  by `dart run scripts/gen_installers.dart`.
:: ═══════════════════════════════════════════════════════════════════════════

:: The banner and status glyphs are UTF-8; switch the console code page so
:: cmd.exe does not print them as mojibake.
chcp 65001 >nul

powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://fa1.dev/install.ps1 | iex"

:: Make fa usable in THIS console too: the user-PATH update above only takes
:: effect in NEW windows, and the child PowerShell's session refresh dies
:: with it. Batch files run in-process in cmd.exe, so this set persists.
set "PATH=%LOCALAPPDATA%\Fa\bin;%PATH%"
echo.
echo fa is ready in THIS console. For other windows, open a NEW terminal.
