# install.ps1 — non-interactive one-line installer for the Fa CLI on Windows.
#                 Works when piped:
#                   irm https://fa1.dev/install.ps1 | iex
#
# What it does:
#   1. Checks that the Dart SDK (dart.exe) is on PATH.
#   2. Installs (or updates) flutter_agent_harness from pub.dev.
#   3. Ensures the pub cache bin directory is on the user PATH.
#   4. Prints a concise setup recipe and exits.
#
# For interactive configuration (provider, model, API key), run:
#   irm https://fa1.dev/setup.ps1 | iex
#
# ═══════════════════════════════════════════════════════════════════════════
#  DO NOT EDIT THIS FILE BY HAND. It is generated from site/install-config.yaml
#  by `dart run scripts/gen_installers.dart`.
# ═══════════════════════════════════════════════════════════════════════════

#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$Package = "flutter_agent_harness"

# ── Output helpers ───────────────────────────────────────────────────────────
function Write-Info($msg) { Write-Host "→ $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "✔ $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "! $msg" -ForegroundColor Yellow }
function Write-Err($msg) { Write-Host "✘ $msg" -ForegroundColor Red }

# ── Banner ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ███████╗ █████╗       ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗"
Write-Host "  ██╔════╝██╔══██╗      ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║"
Write-Host "  █████╗  ███████║█████╗   ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║"
Write-Host "  ██╔══╝  ██╔══██║╚════╝   ██║   ╚════╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║"
Write-Host "  ██║     ██║  ██║         ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗"
Write-Host "  ╚═╝     ╚═╝  ╚═╝         ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝"
Write-Host ""
Write-Host "  Fa installer — flutter_agent_harness CLI (Windows)"
Write-Host ""

# ── 1. Dart SDK check ────────────────────────────────────────────────────────
$dart = Get-Command dart -ErrorAction SilentlyContinue
if (-not $dart) {
    Write-Err "the Dart SDK ('dart') is not on your PATH."
    Write-Host ""
    Write-Host "  Fa is distributed via pub.dev and needs the Dart SDK, bundled with Flutter:"
    Write-Host ""
    Write-Host "    https://docs.flutter.dev/get-started/install"
    Write-Host ""
    Write-Host "  Then re-run:"
    Write-Host ""
    Write-Host "    irm https://fa1.dev/install.ps1 | iex"
    Write-Host ""
    exit 1
}
Write-Ok "Dart SDK found at $($dart.Source)"

# ── 2. Activate package from pub.dev ─────────────────────────────────────────
Write-Info "Activating $Package from pub.dev..."
try {
    & dart pub global activate $Package
} catch {
    Write-Err "dart pub global activate failed."
    exit 1
}

# ── 3. Ensure pub cache bin is on the user PATH ──────────────────────────────
$pubCacheBin = $env:PUB_CACHE_BIN
if (-not $pubCacheBin) {
    # Dart's default cache location on Windows.
    $candidate = Join-Path $env:LOCALAPPDATA "Pub\Cache\bin"
    if (-not (Test-Path $candidate)) {
        $candidate = Join-Path $env:APPDATA "Pub\Cache\bin"
    }
    $pubCacheBin = $candidate
}

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$pathParts = $userPath -split ';' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
if ($pubCacheBin -notin $pathParts) {
    Write-Info "Adding pub cache bin to your user PATH: $pubCacheBin"
    $newPath = ($pathParts + $pubCacheBin) -join ';'
    [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
    # Also update the current process so the verification below works.
    $env:Path = ($env:Path -split ';' | ForEach-Object { $_.Trim() } | Where-Object { $_ }) + $pubCacheBin -join ';'
}

# Refresh PATH from the registry in this session.
$env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [Environment]::GetEnvironmentVariable("Path", "User")

$faCmd = Get-Command fa -ErrorAction SilentlyContinue
if (-not $faCmd) { $faCmd = Get-Command fah -ErrorAction SilentlyContinue }
if ($faCmd) {
    Write-Ok "'fa' is on PATH ($($faCmd.Source))."
} else {
    # The registry refresh can occasionally lag; make sure the current process
    # PATH contains the pub cache bin so the command is available immediately.
    $processPaths = $env:Path -split ';' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
    if ($pubCacheBin -notin $processPaths) {
        $env:Path = ($processPaths + $pubCacheBin) -join ';'
    }

    $faCmd = Get-Command fa -ErrorAction SilentlyContinue
    if (-not $faCmd) { $faCmd = Get-Command fah -ErrorAction SilentlyContinue }
    if ($faCmd) {
        Write-Ok "'fa' is now available on PATH ($($faCmd.Source))."
    } else {
        Write-Warn "'fa' is not on PATH yet. The executable lives in $pubCacheBin"
        Write-Host ""
        Write-Warn "Open a new PowerShell window, or run this in the current one:"
        Write-Host ""
        Write-Host "    `$env:Path = `$env:Path + ';$pubCacheBin'"
        Write-Host ""
    }
}

# ── 4. Done ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Ok "Installation complete."
Write-Host ""
Write-Host "  Configure a provider and API key interactively:"
Write-Host ""
Write-Host "    irm https://fa1.dev/setup.ps1 | iex"
Write-Host ""
Write-Host "  Or set an environment variable manually:"
Write-Host ""
Write-Host "    `$env:OPENROUTER_API_KEY = '<your-key>'   # or ANTHROPIC_API_KEY / GOOGLE_API_KEY / OPENAI_API_KEY"
Write-Host ""
Write-Host "  Then start the agent:"
Write-Host ""
Write-Host "    fa"
Write-Host ""
Write-Host "  Or run a single headless task:"
Write-Host ""
Write-Host "    fa `"summarize CHANGELOG.md`""
Write-Host ""
Write-Host "  (the legacy command 'fah' also works)"
Write-Host ""
Write-Host "  Docs:    https://github.com/IstiN/flutter_agent_harness"
Write-Host "  Package: https://pub.dev/packages/flutter_agent_harness"
Write-Host ""
