#!/usr/bin/env bash
# setup.sh — interactive configuration wizard for the Fa CLI.
#              Run this after `install.sh` to pick a provider, model, API key,
#              mode and approval policy.
#
#                curl -fsSL "https://fa1.dev/setup.sh" | sh
#
# What it does:
#   1. Verifies `fa` is installed.
#   2. Interactively picks a provider + model (or a custom endpoint).
#   3. Collects the API key and writes ~/.fah/config.yaml.
#   4. Optionally persists the API key in your shell startup file.
#
# ═══════════════════════════════════════════════════════════════════════════
#  DO NOT EDIT THIS FILE BY HAND. It is generated from site/install-config.yaml
#  by `dart run scripts/gen_installers.dart`.
# ═══════════════════════════════════════════════════════════════════════════

set -eu  # no pipefail: dash (Ubuntu sh) lacks it

FAH_CONFIG_DIR="$HOME/.fah"
FAH_CONFIG_FILE="$FAH_CONFIG_DIR/config.yaml"

# ── TTY handling ─────────────────────────────────────────────────────────────
if [ -t 0 ]; then
  FAH_TTY="/dev/stdin"
else
  FAH_TTY="/dev/tty"
fi

# ── Output helpers ───────────────────────────────────────────────────────────
say() {
  printf '%s\n' "$*"
}

info() {
  printf '\033[1;34m→\033[0m %s\n' "$*"
}

ok() {
  printf '\033[1;32m✔\033[0m %s\n' "$*"
}

warn() {
  printf '\033[1;33m!\033[0m %s\n' "$*" >&2
}

err() {
  printf '\033[1;31m✘\033[0m %s\n' "$*" >&2
}

# ── Interactive helpers ──────────────────────────────────────────────────────
prompt() {
  local text="$1"
  printf '\033[1m%s\033[0m ' "$text" > /dev/tty
}

ask() {
  local var="$1" text="$2" default="${3:-}"
  while true; do
    if [ -n "$default" ]; then
      prompt "$text [$default]"
    else
      prompt "$text"
    fi
    local value
    if ! read -r value < "$FAH_TTY" 2>/dev/tty; then
      printf -v "$var" '%s' "$default"
      return 1
    fi
    if [ -z "$value" ] && [ -n "$default" ]; then
      value=$default
    fi
    printf -v "$var" '%s' "$value"
    return 0
  done
}

ask_hidden() {
  local var="$1" text="$2"
  prompt "$text"
  local value
  if ! read -rs value < "$FAH_TTY" 2>/dev/tty; then
    printf -v "$var" ''
    return 1
  fi
  printf '\n' > /dev/tty
  printf -v "$var" '%s' "$value"
  return 0
}

ask_yn() {
  local var="$1" text="$2" default="${3:-y}"
  local answer
  while true; do
    if [ "$default" = "y" ]; then
      prompt "$text [Y/n]"
    else
      prompt "$text [y/N]"
    fi
    if ! read -r answer < "$FAH_TTY" 2>/dev/tty; then
      printf -v "$var" '%s' "$default"
      return 1
    fi
    answer=${answer:-$default}
    case "$answer" in
      [Yy]|"" ) printf -v "$var" 'y'; return 0 ;;
      [Nn]    ) printf -v "$var" 'n'; return 0 ;;
    esac
    warn "please answer y or n"
  done
}

# ── Banner ───────────────────────────────────────────────────────────────────
say ""
say "  ███████╗ █████╗       ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗"
say "  ██╔════╝██╔══██╗      ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║"
say "  █████╗  ███████║█████╗   ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║"
say "  ██╔══╝  ██╔══██║╚════╝   ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║"
say "  ██║     ██║  ██║         ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗"
say "  ╚═╝     ╚═╝  ╚═╝         ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝"
say ""
say "  Fa setup wizard — flutter_agent_harness CLI"
say ""

# ── 1. Verify CLI is installed ───────────────────────────────────────────────
if ! command -v fa >/dev/null 2>&1 && ! command -v fah >/dev/null 2>&1; then
  err "'fa' is not on your PATH."
  say ""
  say "  Run the installer first:"
  say ""
  say "    curl -fsSL \"https://fa1.dev/install.sh\" | sh"
  say ""
  say "  Then reload your shell (or open a new terminal) and run this wizard again:"
  say ""
  say "    curl -fsSL \"https://fa1.dev/setup.sh\" | sh"
  say ""
  exit 1
fi
ok "Found 'fa' on PATH ($(command -v fa 2>/dev/null || command -v fah))."

# ── 2. Interactive configuration ─────────────────────────────────────────────
if [ ! -e /dev/tty ] || [ ! -t 2 ]; then
  info "Non-interactive environment detected."
  say ""
  say "  To finish setup, set an API key and run:"
  say ""
  say "    fa"
  say ""
  exit 0
fi

if [ -f "$FAH_CONFIG_FILE" ]; then
  reconfigure="n"
  ask_yn reconfigure "A config already exists at ${FAH_CONFIG_FILE}. Reconfigure?" "n"
  if [ "$reconfigure" != "y" ]; then
    ok "Kept existing config. Run 'fa' to start."
    exit 0
  fi
fi

say ""
info "Let's configure your default provider and model."
say ""

# Provider menu
say "  1) OpenRouter  — one key, many models   (recommended)"
say "  2) Anthropic  — Claude"
say "  3) Google  — Gemini"
say "  4) OpenAI  — GPT"
say "  5) Custom  — any OpenAI-compatible endpoint"
say ""
provider_choice=""
while true; do
  ask provider_choice "Pick a provider [1-5]" "1"
  case "$provider_choice" in
    1|openrouter) provider="openrouter"; provider_kind="openai-completions"; break ;;
    2|anthropic) provider="anthropic"; provider_kind="anthropic"; break ;;
    3|google) provider="google"; provider_kind="google"; break ;;
    4|openai) provider="openai"; provider_kind="openai-completions"; break ;;
    5|custom) provider="custom"; provider_kind="openai-completions"; break ;;
    *) warn "enter 1-5" ;;
  esac
done


# Model selection
model=""
base_url=""
case "$provider" in
  openrouter)
    say ""
    say "  OpenRouter models:"
    say "    1) anthropic/claude-sonnet-4   (recommended)"
    say "    2) openai/gpt-4o-mini"
    say "    3) google/gemini-2.5-pro"
    say "    4) anthropic/claude-opus-4"
    say "    5) openai/gpt-4.1-mini"
    say "    6) other — enter model id manually"
    while true; do
      ask model "Pick a model" "1"
      case "$model" in
        1) model="anthropic/claude-sonnet-4"; break ;;
        2) model="openai/gpt-4o-mini"; break ;;
        3) model="google/gemini-2.5-pro"; break ;;
        4) model="anthropic/claude-opus-4"; break ;;
        5) model="openai/gpt-4.1-mini"; break ;;
        6) ask model "Enter the OpenRouter model id"; break ;;
        *) warn "enter 1-6" ;;
      esac
    done
    base_url="https://openrouter.ai/api/v1"
    key_var="OPENROUTER_API_KEY"
    ;;
  anthropic)
    say ""
    say "  Anthropic models:"
    say "    1) claude-sonnet-4-5   (recommended)"
    say "    2) claude-opus-4"
    say "    3) claude-haiku-4"
    say "    4) other — enter model id manually"
    while true; do
      ask model "Pick a model" "1"
      case "$model" in
        1) model="claude-sonnet-4-5"; break ;;
        2) model="claude-opus-4"; break ;;
        3) model="claude-haiku-4"; break ;;
        4) ask model "Enter the Anthropic model id"; break ;;
        *) warn "enter 1-4" ;;
      esac
    done
    base_url="https://api.anthropic.com"
    key_var="ANTHROPIC_API_KEY"
    ;;
  google)
    say ""
    say "  Google models:"
    say "    1) gemini-2.5-pro   (recommended)"
    say "    2) gemini-2.0-flash"
    say "    3) other — enter model id manually"
    while true; do
      ask model "Pick a model" "1"
      case "$model" in
        1) model="gemini-2.5-pro"; break ;;
        2) model="gemini-2.0-flash"; break ;;
        3) ask model "Enter the Google model id"; break ;;
        *) warn "enter 1-3" ;;
      esac
    done
    base_url="https://generativelanguage.googleapis.com/v1beta"
    key_var="GOOGLE_API_KEY"
    ;;
  openai)
    say ""
    say "  OpenAI models:"
    say "    1) gpt-4o-mini   (recommended)"
    say "    2) gpt-4o"
    say "    3) gpt-4.1-mini"
    say "    4) other — enter model id manually"
    while true; do
      ask model "Pick a model" "1"
      case "$model" in
        1) model="gpt-4o-mini"; break ;;
        2) model="gpt-4o"; break ;;
        3) model="gpt-4.1-mini"; break ;;
        4) ask model "Enter the OpenAI model id"; break ;;
        *) warn "enter 1-4" ;;
      esac
    done
    base_url="https://api.openai.com/v1"
    key_var="OPENAI_API_KEY"
    ;;
  custom)
    say ""
    ask base_url "Custom base URL (e.g. http://localhost:11434/v1)"
    ask model "Model id on that endpoint"
    key_var="OPENAI_API_KEY"
    ;;
esac


# API key
say ""
api_key=""
if [ "$provider" = "custom" ]; then
  ask_yn needs_key "Does this endpoint require an API key?" "n"
  if [ "$needs_key" = "y" ]; then
    ask_hidden api_key "Paste your API key"
  fi
else
  ask_hidden api_key "Paste your ${key_var}"
fi

# Mode selection
say ""
say "  Agent modes:"
say "    1) code (default)  — edit/run code"
say "    2) architect  — plan and review"
say "    3) review  — audit and suggest"


mode=""
while true; do
  ask mode "Pick a mode" "1"
  case "$mode" in
    1|code) mode="code"; break ;;
    2|architect) mode="architect"; break ;;
    3|review) mode="review"; break ;;
    *) warn "enter 1-3" ;;
  esac
done


# Approval mode
say ""
say "  Tool approval:"
say "    1) yolo (default)  — run safe tools unattended"
say "    2) write  — prompt before writes/executes"
say "    3) always-ask  — prompt before every tool call"


approval=""
while true; do
  ask approval "Pick an approval mode" "1"
  case "$approval" in
    1|yolo) approval="yolo"; break ;;
    2|write) approval="write"; break ;;
    3|always-ask) approval="always-ask"; break ;;
    *) warn "enter 1-3" ;;
  esac
done


# Write config.yaml
mkdir -p "$FAH_CONFIG_DIR"
cat > "$FAH_CONFIG_FILE" <<EOF
provider: ${provider_kind}
model: ${model}
baseUrl: ${base_url}
mode: ${mode}
approvalMode: ${approval}
allowedTools: []
EOF
ok "Wrote ${FAH_CONFIG_FILE}"

# Persist API key in shell startup file
if [ -n "$api_key" ]; then
  say ""
  shell_rc=""
  case "${SHELL:-}" in
    */zsh)  shell_rc="$HOME/.zshrc" ;;
    */bash) shell_rc="$HOME/.bashrc" ;;
    */fish) shell_rc="$HOME/.config/fish/config.fish" ;;
  esac

  if [ -n "$shell_rc" ]; then
    persist="n"
    ask_yn persist "Add ${key_var} to ${shell_rc}? (we never log the value)" "y"
    if [ "$persist" = "y" ]; then
      if [ -f "$shell_rc" ] && grep -qF "export ${key_var}=" "$shell_rc" 2>/dev/null; then
        sed -i.bak "s|^export ${key_var}=.*|export ${key_var}='${api_key}'|" "$shell_rc" && rm -f "${shell_rc}.bak"
      else
        printf "\n# Fa CLI API key\nexport %s='%s'\n" "$key_var" "$api_key" >> "$shell_rc"
      fi
      ok "Saved ${key_var} to ${shell_rc}"
      ok "Reload your shell or run: source ${shell_rc}"
    else
      say ""
      say "  Add this to your environment manually:"
      say ""
      say "    export ${key_var}=<your-key>"
      say ""
    fi
  else
    say ""
    say "  Add this to your environment manually:"
    say ""
    say "    export ${key_var}=<your-key>"
    say ""
  fi
fi

# ── 3. Done ──────────────────────────────────────────────────────────────────
say ""
ok "Configuration complete."
say ""
say "  Start the agent:"
say ""
say "    fa"
say ""
say "  Or run a single headless task:"
say ""
say "    fa \"summarize CHANGELOG.md\""
say ""
say "  (the legacy command 'fah' also works)"
say ""
