# setup.ps1 — interactive configuration wizard for the Fa CLI on Windows.
#             Run this after `install.ps1` to pick a provider, model, API key,
#             mode and approval policy.
#
#               irm https://fa1.dev/setup.ps1 | iex
#
# What it does:
#   1. Verifies `fa` is installed.
#   2. Interactively picks a provider + model (or a custom endpoint).
#   3. Collects the API key and writes ~\.fah\config.yaml.
#   4. Optionally persists the API key as a user environment variable.
#
# ═══════════════════════════════════════════════════════════════════════════
#  DO NOT EDIT THIS FILE BY HAND. It is generated from site/install-config.yaml
#  by `dart run scripts/gen_installers.dart`.
# ═══════════════════════════════════════════════════════════════════════════

#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$FahConfigDir = Join-Path $env:USERPROFILE ".fah"
$FahConfigFile = Join-Path $FahConfigDir "config.yaml"

# ── Output helpers ───────────────────────────────────────────────────────────
function Write-Info($msg) { Write-Host "→ $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "✔ $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "! $msg" -ForegroundColor Yellow }
function Write-Err($msg) { Write-Host "✘ $msg" -ForegroundColor Red }

# ── Banner ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ███████╗ █████╗       ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗"
Write-Host "  ██╔════╝██╔══██╗      ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║"
Write-Host "  █████╗  ███████║█████╗   ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║"
Write-Host "  ██╔══╝  ██╔══██║╚════╝   ██║   ╚════╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║"
Write-Host "  ██║     ██║  ██║         ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗"
Write-Host "  ╚═╝     ╚═╝  ╚═╝         ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝"
Write-Host ""
Write-Host "  Fa setup wizard — flutter_agent_harness CLI (Windows)"
Write-Host ""

# ── 1. Verify CLI is installed ───────────────────────────────────────────────
$faCmd = Get-Command fa -ErrorAction SilentlyContinue
if (-not $faCmd) { $faCmd = Get-Command fah -ErrorAction SilentlyContinue }
if (-not $faCmd) {
    Write-Err "'fa' is not on your PATH."
    Write-Host ""
    Write-Host "  Run the installer first:"
    Write-Host ""
    Write-Host "    irm https://fa1.dev/install.ps1 | iex"
    Write-Host ""
    Write-Host "  Then open a new PowerShell window and run this wizard again:"
    Write-Host ""
    Write-Host "    irm https://fa1.dev/setup.ps1 | iex"
    Write-Host ""
    exit 1
}
Write-Ok "Found 'fa' on PATH ($($faCmd.Source))."

# ── 2. Interactive configuration ─────────────────────────────────────────────
# When invoked as `irm ... | iex`, stdin is the script text — skip prompts.
if ([System.Console]::IsInputRedirected) {
    Write-Info "Non-interactive environment detected."
    Write-Host ""
    Write-Host "  To finish setup, set an API key and run:"
    Write-Host ""
    Write-Host "    fa"
    Write-Host ""
    exit 0
}

if (Test-Path $FahConfigFile) {
    $reconfigure = Read-Host "A config already exists at $FahConfigFile. Reconfigure? [y/N]"
    if ($reconfigure -notmatch '^[Yy]') {
        Write-Ok "Kept existing config. Run 'fa' to start."
        exit 0
    }
}

Write-Host ""
Write-Info "Let's configure your default provider and model."
Write-Host ""

function Read-Choice($prompt, $valid) {
    while ($true) {
        $value = Read-Host $prompt
        if ($valid -contains $value) { return $value }
        Write-Warn "enter one of: $($valid -join ', ')"
    }
}

function Read-Secure($prompt) {
    $secure = Read-Host $prompt -AsSecureString
    $cred = New-Object System.Net.NetworkCredential("", $secure)
    return $cred.Password
}

# Provider menu
Write-Host "  1) OpenRouter  — one key, many models   (recommended)"
Write-Host "  2) Anthropic  — Claude"
Write-Host "  3) Google  — Gemini"
Write-Host "  4) OpenAI  — GPT"
Write-Host "  5) Custom  — any OpenAI-compatible endpoint"
Write-Host ""
$providerChoice = Read-Choice "Pick a provider [1-5]" @("1", "2", "3", "4", "5", "openrouter", "anthropic", "google", "openai", "custom")


switch -Regex ($providerChoice) {
    "^(1|openrouter)$" {
        $provider = "openrouter"
        $providerKind = "openai-completions"
        Write-Host ""
        Write-Host "  OpenRouter models:"
        Write-Host "    1) anthropic/claude-sonnet-4   (recommended)"
        Write-Host "    2) openai/gpt-4o-mini"
        Write-Host "    3) google/gemini-2.5-pro"
        Write-Host "    4) anthropic/claude-opus-4"
        Write-Host "    5) openai/gpt-4.1-mini"
        Write-Host "    6) other — enter model id manually"
        $m = Read-Choice "Pick a model [1-6]" @("1", "2", "3", "4", "5", "6")
        switch ($m) {
            "1" { $model = "anthropic/claude-sonnet-4" }
            "2" { $model = "openai/gpt-4o-mini" }
            "3" { $model = "google/gemini-2.5-pro" }
            "4" { $model = "anthropic/claude-opus-4" }
            "5" { $model = "openai/gpt-4.1-mini" }
            "6" { $model = Read-Host "Enter the OpenRouter model id" }
        }
        $baseUrl = "https://openrouter.ai/api/v1"
        $keyVar = "OPENROUTER_API_KEY"
    }
    "^(2|anthropic)$" {
        $provider = "anthropic"
        $providerKind = "anthropic"
        Write-Host ""
        Write-Host "  Anthropic models:"
        Write-Host "    1) claude-sonnet-4-5   (recommended)"
        Write-Host "    2) claude-opus-4"
        Write-Host "    3) claude-haiku-4"
        Write-Host "    4) other — enter model id manually"
        $m = Read-Choice "Pick a model [1-4]" @("1", "2", "3", "4")
        switch ($m) {
            "1" { $model = "claude-sonnet-4-5" }
            "2" { $model = "claude-opus-4" }
            "3" { $model = "claude-haiku-4" }
            "4" { $model = Read-Host "Enter the Anthropic model id" }
        }
        $baseUrl = "https://api.anthropic.com"
        $keyVar = "ANTHROPIC_API_KEY"
    }
    "^(3|google)$" {
        $provider = "google"
        $providerKind = "google"
        Write-Host ""
        Write-Host "  Google models:"
        Write-Host "    1) gemini-2.5-pro   (recommended)"
        Write-Host "    2) gemini-2.0-flash"
        Write-Host "    3) other — enter model id manually"
        $m = Read-Choice "Pick a model [1-3]" @("1", "2", "3")
        switch ($m) {
            "1" { $model = "gemini-2.5-pro" }
            "2" { $model = "gemini-2.0-flash" }
            "3" { $model = Read-Host "Enter the Google model id" }
        }
        $baseUrl = "https://generativelanguage.googleapis.com/v1beta"
        $keyVar = "GOOGLE_API_KEY"
    }
    "^(4|openai)$" {
        $provider = "openai"
        $providerKind = "openai-completions"
        Write-Host ""
        Write-Host "  OpenAI models:"
        Write-Host "    1) gpt-4o-mini   (recommended)"
        Write-Host "    2) gpt-4o"
        Write-Host "    3) gpt-4.1-mini"
        Write-Host "    4) other — enter model id manually"
        $m = Read-Choice "Pick a model [1-4]" @("1", "2", "3", "4")
        switch ($m) {
            "1" { $model = "gpt-4o-mini" }
            "2" { $model = "gpt-4o" }
            "3" { $model = "gpt-4.1-mini" }
            "4" { $model = Read-Host "Enter the OpenAI model id" }
        }
        $baseUrl = "https://api.openai.com/v1"
        $keyVar = "OPENAI_API_KEY"
    }
    "^(5|custom)$" {
        $provider = "custom"
        $providerKind = "openai-completions"
        $baseUrl = Read-Host "Custom base URL (e.g. http://localhost:11434/v1)"
        $model = Read-Host "Model id on that endpoint"
        $keyVar = "OPENAI_API_KEY"
    }
}


# API key
Write-Host ""
$apiKey = ""
if ($provider -eq "custom") {
    $needsKey = Read-Host "Does this endpoint require an API key? [y/N]"
    if ($needsKey -match '^[Yy]') {
        $apiKey = Read-Secure "Paste your API key"
    }
} else {
    $apiKey = Read-Secure "Paste your $keyVar"
}

# Mode selection
Write-Host ""
Write-Host "  Agent modes:"
Write-Host "    1) code (default)  — edit/run code"
Write-Host "    2) architect  — plan and review"
Write-Host "    3) review  — audit and suggest"


$modeChoice = Read-Choice "Pick a mode [1-3]" @("1", "code", "2", "architect", "3", "review")
switch -Regex ($modeChoice) {
    "^(1|code)$" { $mode = "code" }
    "^(2|architect)$" { $mode = "architect" }
    "^(3|review)$" { $mode = "review" }
}


# Approval mode
Write-Host ""
Write-Host "  Tool approval:"
Write-Host "    1) yolo (default)  — run safe tools unattended"
Write-Host "    2) write  — prompt before writes/executes"
Write-Host "    3) always-ask  — prompt before every tool call"


$approvalChoice = Read-Choice "Pick an approval mode [1-3]" @("1", "yolo", "2", "write", "3", "always-ask")
switch -Regex ($approvalChoice) {
    "^(1|yolo)$" { $approval = "yolo" }
    "^(2|write)$" { $approval = "write" }
    "^(3|always-ask)$" { $approval = "always-ask" }
}


# Write config.yaml
New-Item -ItemType Directory -Force -Path $FahConfigDir | Out-Null
@"
provider: $providerKind
model: $model
baseUrl: $baseUrl
mode: $mode
approvalMode: $approval
allowedTools: []
"@ | Set-Content -Path $FahConfigFile -Encoding UTF8
Write-Ok "Wrote $FahConfigFile"

# Persist API key as a user environment variable
if ($apiKey) {
    Write-Host ""
    $persist = Read-Host "Add $keyVar to your user environment variables? [Y/n]"
    if ($persist -notmatch '^[Nn]') {
        [Environment]::SetEnvironmentVariable($keyVar, $apiKey, "User")
        Set-Item "Env:$keyVar" $apiKey
        Write-Ok "Saved $keyVar to your user environment variables."
        Write-Host "  Open a new PowerShell window, or run: `$env:$keyVar = '$apiKey'"
    } else {
        Write-Host ""
        Write-Host "  Add this to your environment manually:"
        Write-Host ""
        Write-Host "    `$env:$keyVar = '<your-key>'"
        Write-Host ""
    }
}

# ── 3. Done ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Ok "Configuration complete."
Write-Host ""
Write-Host "  Start the agent:"
Write-Host ""
Write-Host "    fa"
Write-Host ""
Write-Host "  Or run a single headless task:"
Write-Host ""
Write-Host "    fa `"summarize CHANGELOG.md`""
Write-Host ""
Write-Host "  (the legacy command 'fah' also works)"
Write-Host ""
