// Symbol presets (issue #804): the TUI glyph vocabulary — box drawing,
// separators (incl. powerline caps), status/nav glyphs, thinking-level
// labels, checkboxes, markdown formatting and the icon/tool sets the S2-S6
// stories consume. Token-for-token from omp pinned df624f5
// (packages/tui/src/theme/symbols.ts: UNICODE/NERD/ASCII_SYMBOLS +
// SPINNER_FRAMES), trimmed to the families fa renders. The ascii preset
// carries zero non-ASCII code points — it can never emit a nerd glyph.

// ignore_for_file: constant_identifier_names

/// One symbol preset: a omp-keyed glyph map plus the two spinner frame
/// rings (status spinner, activity/working loader).
final class TuiSymbols {
  const TuiSymbols({
    required this.name,
    required this.glyphs,
    required this.statusSpinner,
    required this.activitySpinner,
  });

  final String name;

  /// omp symbol key (e.g. `sep.dot`, `boxRound.topLeft`) -> glyph.
  final Map<String, String> glyphs;

  /// The status spinner frames (omp `SPINNER_FRAMES[preset].status`).
  final List<String> statusSpinner;

  /// The activity loader frames (omp ``...activity`` — braille dots).
  final List<String> activitySpinner;

  /// The glyph for [key]; asserts in debug that the key exists (omp keys
  /// are a closed vocabulary the S2-S6 stories code against) and renders
  /// empty in release rather than leaking a null.
  String glyph(String key) {
    final value = glyphs[key];
    assert(value != null, 'unknown symbol key: $key');
    return value ?? '';
  }
}
/// The omp `unicode` preset.
const TuiSymbols kTuiSymbolsUnicode = TuiSymbols(
  name: 'unicode',
  glyphs: {
    'status.success': '✔',
    'status.error': '✘',
    'status.warning': '⚠',
    'status.info': 'ⓘ',
    'status.pending': '⏳',
    'status.disabled': '⦸',
    'status.enabled': '●',
    'status.running': '⟳',
    'status.shadowed': '○',
    'status.aborted': '⏹',
    'status.done': '•',
    'nav.cursor': '❯',
    'nav.selected': '➤',
    'nav.expand': '▸',
    'nav.collapse': '▾',
    'nav.back': '⟵',
    'tree.branch': '├─',
    'tree.last': '└─',
    'tree.vertical': '│',
    'tree.horizontal': '─',
    'tree.hook': '└',
    'progress.filled': '━',
    'progress.empty': '─',
    'context.speculation': '╎',
    'context.compaction': '┃',
    'boxRound.topLeft': '╭',
    'boxRound.topRight': '╮',
    'boxRound.bottomLeft': '╰',
    'boxRound.bottomRight': '╯',
    'boxRound.horizontal': '─',
    'boxRound.vertical': '│',
    'boxDotted.horizontal': '┄',
    'boxDotted.vertical': '┆',
    'boxSharp.topLeft': '┌',
    'boxSharp.topRight': '┐',
    'boxSharp.bottomLeft': '└',
    'boxSharp.bottomRight': '┘',
    'boxSharp.horizontal': '─',
    'boxSharp.vertical': '│',
    'boxSharp.cross': '┼',
    'boxSharp.teeDown': '┬',
    'boxSharp.teeUp': '┴',
    'boxSharp.teeRight': '├',
    'boxSharp.teeLeft': '┤',
    'sep.powerline': '▕',
    'sep.powerlineThin': '┆',
    'sep.powerlineLeft': '▶',
    'sep.powerlineRight': '◀',
    'sep.powerlineThinLeft': '>',
    'sep.powerlineThinRight': '<',
    'sep.powerlineCapLeft': '',
    'sep.block': '▌',
    'sep.space': ' ',
    'sep.asciiLeft': '>',
    'sep.asciiRight': '<',
    'sep.dot': ' · ',
    'sep.slash': ' / ',
    'sep.pipe': ' │ ',
    'icon.model': '⬢',
    'icon.plan': '🗺',
    'icon.prewalk': '🏃',
    'icon.goal': '🎯',
    'icon.pause': '⏸',
    'icon.loop': '↻',
    'icon.folder': '📁',
    'icon.worktree': '🌳',
    'icon.search': '🔍',
    'icon.scratchFolder': '🗑',
    'icon.file': '📄',
    'icon.git': '⎇',
    'icon.branch': '⑂',
    'icon.pr': '⤴',
    'icon.pin': '📌',
    'icon.tokens': '🪙',
    'icon.context': '◫',
    'icon.cost': '💲',
    'icon.subscription': '(sub)',
    'icon.advisor': '👁',
    'icon.advisorClosed': '🙈',
    'icon.time': '⏱',
    'icon.omp': 'π',
    'icon.esc': '⎋',
    'icon.ghost': '👻',
    'icon.agents': '👥',
    'icon.job': '⚙',
    'icon.cache': '💾',
    'icon.cacheMiss': '⊘',
    'icon.input': '⤵',
    'icon.output': '⤴',
    'icon.throughput': '⚡',
    'icon.intelligence': '🧠',
    'icon.host': '🖥',
    'icon.session': '🆔',
    'icon.package': '📦',
    'icon.warning': '⚠',
    'icon.rewind': '↶',
    'icon.auto': '⟲',
    'icon.fast': '⚡',
    'icon.mic': '🎤',
    'icon.camera': '📷',
    'thinking.minimal': '○ min',
    'thinking.low': '◔ low',
    'thinking.medium': '◑ med',
    'thinking.high': '◒ high',
    'thinking.xhigh': '◕ xhigh',
    'thinking.max': '◉ max',
    'thinking.autoPending': '⟳',
    'checkbox.checked': '☑',
    'checkbox.unchecked': '☐',
    'radio.selected': '◉',
    'radio.unselected': '○',
    'format.bullet': '•',
    'format.dash': '—',
    'format.bracketLeft': '⟦',
    'format.bracketRight': '⟧',
    'md.quoteBorder': '▏',
    'md.hrChar': '─',
    'md.bullet': '•',
    'md.colorSwatch': '■',
    'tool.write': '✎',
    'tool.edit': '✎',
    'tool.bash': '❯',
    'tool.ssh': '⇄',
    'tool.lsp': '💡',
    'tool.gh': '⎇',
    'tool.webSearch': '⌕',
    'tool.exa': '🔭',
    'tool.browser': '🌐',
    'tool.eval': '▶',
    'tool.debug': '🐞',
    'tool.mcp': '🔌',
    'tool.job': '⚙',
    'tool.launch': '🚀',
    'tool.task': '⇶',
    'tool.todo': '☑',
    'tool.memory': '🧠',
    'tool.ask': '?',
    'tool.resolve': '✓',
    'tool.review': '◉',
    'tool.goal': '◎',
    'tool.irc': '✉',
    'tool.delete': '🗑',
    'tool.move': '➜',
  },
  statusSpinner: ['⣾', '⣽', '⣻', '⢿', '⡿', '⣟', '⣯', '⣷'],
  activitySpinner: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'],
);

/// The omp `nerd` preset.
const TuiSymbols kTuiSymbolsNerd = TuiSymbols(
  name: 'nerd',
  glyphs: {
    'status.success': '\uf00c',
    'status.error': '\uf00d',
    'status.warning': '\uf12a',
    'status.info': '\uf129',
    'status.pending': '\uf254',
    'status.disabled': '\uf05e',
    'status.enabled': '\uf111',
    'status.running': '\uf110',
    'status.shadowed': '\uf10c',
    'status.aborted': '\uf04d',
    'status.done': '•',
    'nav.cursor': '\uf054',
    'nav.selected': '\uf178',
    'nav.expand': '\uf0da',
    'nav.collapse': '\uf0d7',
    'nav.back': '\uf060',
    'tree.branch': '├─',
    'tree.last': '└─',
    'tree.vertical': '│',
    'tree.horizontal': '─',
    'tree.hook': '└',
    'progress.filled': '━',
    'progress.empty': '─',
    'context.speculation': '\u{f055d}',
    'context.compaction': '\u{f0068}',
    'boxRound.topLeft': '╭',
    'boxRound.topRight': '╮',
    'boxRound.bottomLeft': '╰',
    'boxRound.bottomRight': '╯',
    'boxRound.horizontal': '─',
    'boxRound.vertical': '│',
    'boxDotted.horizontal': '┄',
    'boxDotted.vertical': '┆',
    'boxSharp.topLeft': '┌',
    'boxSharp.topRight': '┐',
    'boxSharp.bottomLeft': '└',
    'boxSharp.bottomRight': '┘',
    'boxSharp.horizontal': '─',
    'boxSharp.vertical': '│',
    'boxSharp.cross': '┼',
    'boxSharp.teeDown': '┬',
    'boxSharp.teeUp': '┴',
    'boxSharp.teeRight': '├',
    'boxSharp.teeLeft': '┤',
    'sep.powerline': '\ue0b0',
    'sep.powerlineThin': '\ue0b1',
    'sep.powerlineLeft': '\ue0b0',
    'sep.powerlineRight': '\ue0b2',
    'sep.powerlineThinLeft': '\ue0b1',
    'sep.powerlineThinRight': '\ue0b3',
    'sep.powerlineCapLeft': '\ue0b6',
    'sep.block': '█',
    'sep.space': ' ',
    'sep.asciiLeft': '>',
    'sep.asciiRight': '<',
    'sep.dot': ' · ',
    'sep.slash': '\ue0bb',
    'sep.pipe': '\ue0b3',
    'icon.model': '\uec19',
    'icon.plan': '\uf2d2',
    'icon.prewalk': '\uf29d',
    'icon.goal': '\uf140',
    'icon.pause': '\uf04c',
    'icon.loop': '\uf021',
    'icon.folder': '\uf115',
    'icon.worktree': '\uf0e8',
    'icon.search': '\uf002',
    'icon.scratchFolder': '\uf014',
    'icon.file': '\uf15b',
    'icon.git': '\uf1d3',
    'icon.branch': '\uf126',
    'icon.pr': '\uea64',
    'icon.pin': '\uf08d',
    'icon.tokens': '\ue26b',
    'icon.context': '\ue70f',
    'icon.cost': '\uf155',
    'icon.subscription': '\u{f067a}',
    'icon.advisor': '\uea70',
    'icon.advisorClosed': '\ueae7',
    'icon.time': '\uf017',
    'icon.omp': '\u{f0d57}',
    'icon.esc': '\u{f12b7}',
    'icon.ghost': '\u{f02a0}',
    'icon.agents': '\uf0c0',
    'icon.job': '\uf013',
    'icon.cache': '\uf1c0',
    'icon.cacheMiss': '\uf05e',
    'icon.input': '\uf090',
    'icon.output': '\uf08b',
    'icon.throughput': '\uf0e4',
    'icon.intelligence': '\uee9c',
    'icon.host': '\uf109',
    'icon.session': '\u{f0051}',
    'icon.package': '\uf487',
    'icon.warning': '\uf071',
    'icon.rewind': '\uf0e2',
    'icon.auto': '\u{f0068}',
    'icon.fast': '\uf0e7',
    'icon.mic': '\uf130',
    'icon.camera': '\uf083',
    'thinking.minimal': '\u{f0a9e} min',
    'thinking.low': '\u{f0a9f} low',
    'thinking.medium': '\u{f0aa1} med',
    'thinking.high': '\u{f0aa3} high',
    'thinking.xhigh': '\u{f0aa5} xhi',
    'thinking.max': '\uf06d max',
    'thinking.autoPending': '\uf074',
    'checkbox.checked': '\uf14a',
    'checkbox.unchecked': '\uf096',
    'radio.selected': '\uf192',
    'radio.unselected': '\uf10c',
    'format.bullet': '\uf111',
    'format.dash': '–',
    'format.bracketLeft': '⟨',
    'format.bracketRight': '⟩',
    'md.quoteBorder': '│',
    'md.hrChar': '─',
    'md.bullet': '\uf111',
    'md.colorSwatch': '■',
    'tool.write': '\uea7f',
    'tool.edit': '\uea73',
    'tool.bash': '\uebca',
    'tool.ssh': '\ueb3a',
    'tool.lsp': '\uea61',
    'tool.gh': '\uea84',
    'tool.webSearch': '\ueb01',
    'tool.exa': '\ueb68',
    'tool.browser': '\ueaae',
    'tool.eval': '\uebaf',
    'tool.debug': '\uead8',
    'tool.mcp': '\ueb2d',
    'tool.job': '\ueba2',
    'tool.launch': '\uf135',
    'tool.task': '\uf4a0',
    'tool.todo': '\ueab3',
    'tool.memory': '\ueace',
    'tool.ask': '\ueac7',
    'tool.resolve': '\uebb1',
    'tool.review': '\uea70',
    'tool.goal': '\uebf8',
    'tool.irc': '\uf086',
    'tool.delete': '\uf12d',
    'tool.move': '\uf061',
  },
  statusSpinner: ['\u{f1456}', '\u{f144b}', '\u{f144c}', '\u{f144d}', '\u{f144e}', '\u{f144f}', '\u{f1450}', '\u{f1451}', '\u{f1452}', '\u{f1453}', '\u{f1454}', '\u{f1455}'],
  activitySpinner: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'],
);

/// The omp `ascii` preset.
const TuiSymbols kTuiSymbolsAscii = TuiSymbols(
  name: 'ascii',
  glyphs: {
    'status.success': '[ok]',
    'status.error': '[!!]',
    'status.warning': '[!]',
    'status.info': '[i]',
    'status.pending': '[*]',
    'status.disabled': '[ ]',
    'status.enabled': '[x]',
    'status.running': '[~]',
    'status.shadowed': '[/]',
    'status.aborted': '[-]',
    'status.done': '*',
    'nav.cursor': '>',
    'nav.selected': '->',
    'nav.expand': '+',
    'nav.collapse': '-',
    'nav.back': '<-',
    'tree.branch': '|--',
    'tree.last': '\'--',
    'tree.vertical': '|',
    'tree.horizontal': '-',
    'tree.hook': '`-',
    'progress.filled': '=',
    'progress.empty': '-',
    'context.speculation': ':',
    'context.compaction': '|',
    'boxRound.topLeft': '+',
    'boxRound.topRight': '+',
    'boxRound.bottomLeft': '+',
    'boxRound.bottomRight': '+',
    'boxRound.horizontal': '-',
    'boxRound.vertical': '|',
    'boxDotted.horizontal': '-',
    'boxDotted.vertical': ':',
    'boxSharp.topLeft': '+',
    'boxSharp.topRight': '+',
    'boxSharp.bottomLeft': '+',
    'boxSharp.bottomRight': '+',
    'boxSharp.horizontal': '-',
    'boxSharp.vertical': '|',
    'boxSharp.cross': '+',
    'boxSharp.teeDown': '+',
    'boxSharp.teeUp': '+',
    'boxSharp.teeRight': '+',
    'boxSharp.teeLeft': '+',
    'sep.powerline': '>',
    'sep.powerlineThin': '>',
    'sep.powerlineLeft': '>',
    'sep.powerlineRight': '<',
    'sep.powerlineThinLeft': '>',
    'sep.powerlineThinRight': '<',
    'sep.powerlineCapLeft': '',
    'sep.block': '#',
    'sep.space': ' ',
    'sep.asciiLeft': '>',
    'sep.asciiRight': '<',
    'sep.dot': ' - ',
    'sep.slash': ' / ',
    'sep.pipe': ' | ',
    'icon.model': '[M]',
    'icon.plan': 'plan',
    'icon.prewalk': 'prewalk',
    'icon.goal': 'goal',
    'icon.pause': '||',
    'icon.loop': 'loop',
    'icon.folder': '[D]',
    'icon.worktree': '[wt]',
    'icon.search': '[/]',
    'icon.scratchFolder': '[T]',
    'icon.file': '[F]',
    'icon.git': 'git:',
    'icon.branch': '@',
    'icon.pr': 'PR',
    'icon.pin': '*',
    'icon.tokens': 'tok:',
    'icon.context': 'ctx:',
    'icon.cost': '\$',
    'icon.subscription': '(sub)',
    'icon.advisor': '(adv)',
    'icon.advisorClosed': '(adv)',
    'icon.time': 't:',
    'icon.omp': 'pi',
    'icon.esc': 'esc',
    'icon.ghost': '@',
    'icon.agents': 'AG',
    'icon.job': 'bg',
    'icon.cache': 'cache',
    'icon.cacheMiss': '!',
    'icon.input': 'in:',
    'icon.output': 'out:',
    'icon.throughput': 'tok/s:',
    'icon.intelligence': 'IQ',
    'icon.host': 'host',
    'icon.session': 'id',
    'icon.package': '[P]',
    'icon.warning': '[!]',
    'icon.rewind': '<-',
    'icon.auto': '[A]',
    'icon.fast': '>>',
    'icon.mic': 'MIC',
    'icon.camera': '[o]',
    'thinking.minimal': '[min]',
    'thinking.low': '[low]',
    'thinking.medium': '[med]',
    'thinking.high': '[high]',
    'thinking.xhigh': '[xhi]',
    'thinking.max': '[max]',
    'thinking.autoPending': '[~]',
    'checkbox.checked': '[x]',
    'checkbox.unchecked': '[ ]',
    'radio.selected': '(o)',
    'radio.unselected': '( )',
    'format.bullet': '*',
    'format.dash': '-',
    'format.bracketLeft': '[',
    'format.bracketRight': ']',
    'md.quoteBorder': '|',
    'md.hrChar': '-',
    'md.bullet': '*',
    'md.colorSwatch': '[]',
    'tool.write': '+f',
    'tool.edit': '~',
    'tool.bash': '\$',
    'tool.ssh': 'ssh',
    'tool.lsp': 'lsp',
    'tool.gh': 'gh',
    'tool.webSearch': 'web',
    'tool.exa': 'exa',
    'tool.browser': '[w]',
    'tool.eval': '>_',
    'tool.debug': 'dbg',
    'tool.mcp': '<>',
    'tool.job': 'job',
    'tool.launch': 'run',
    'tool.task': '>>>',
    'tool.todo': '[x]',
    'tool.memory': 'mem',
    'tool.ask': '[?]',
    'tool.resolve': '[v]',
    'tool.review': 'rev',
    'tool.goal': '(o)',
    'tool.irc': '#',
    'tool.delete': 'rm',
    'tool.move': 'mv',
  },
  statusSpinner: ['|', '/', '-', '\\'],
  activitySpinner: ['-', '\\', '|', '/'],
);

/// The symbol preset catalog, keyed by config name.
const Map<String, TuiSymbols> kTuiSymbolPresets = {
  'unicode': kTuiSymbolsUnicode,
  'nerd': kTuiSymbolsNerd,
  'ascii': kTuiSymbolsAscii,
};
