/// AUTO-GENERATED by scripts/sync_codex_models.dart — do not edit.
///
/// Source: openai/codex@main/codex-rs/models-manager/models.json
/// Regenerate: `dart run scripts/sync_codex_models.dart`
///
library;

/// One Codex model entry (mirror of codex-rs bundled model fields).
class CodexModelData {
  const CodexModelData({
    required this.slug,
    required this.contextWindow,
    required this.maxTokens,
  });

  /// The model id (matches [Model.id] from the runtime API).
  final String slug;

  /// The context window the Codex backend reports (input cap).
  final int contextWindow;

  /// The output cap the Codex backend reports.
  final int maxTokens;
}

/// Bundled Codex catalog as of generation time. Source of truth:
/// <https://github.com/openai/codex/blob/main/codex-rs/models-manager/models.json>.
const List<CodexModelData> chatGptCodexBundledModels = <CodexModelData>[
  CodexModelData(slug: 'gpt-5.6-sol', contextWindow: 272000, maxTokens: 16384),
  CodexModelData(slug: 'gpt-5.6-terra', contextWindow: 272000, maxTokens: 16384),
  CodexModelData(slug: 'gpt-5.6-luna', contextWindow: 272000, maxTokens: 16384),
  CodexModelData(slug: 'gpt-5.5', contextWindow: 272000, maxTokens: 16384),
  CodexModelData(slug: 'gpt-5.4', contextWindow: 272000, maxTokens: 16384),
  CodexModelData(slug: 'gpt-5.4-mini', contextWindow: 272000, maxTokens: 16384),
  CodexModelData(slug: 'gpt-5.2', contextWindow: 272000, maxTokens: 16384),
  CodexModelData(slug: 'codex-auto-review', contextWindow: 272000, maxTokens: 16384),
];

/// The Codex default model (the first [chatGptCodexBundledModels] entry, kept separate so the OAuth flow + the picker read the same answer).
const String chatGptCodexBundledDefault = 'gpt-5.6-sol';
