/// The JSONL session record model: the append-only tree of entries that
/// makes up a session, plus the file header.
///
/// Ported from pi-mono `packages/agent/src/harness/types.ts`
/// (`SessionTreeEntry` union) and `harness/session/jsonl-storage.ts`
/// (`SessionHeader`). A session file is a header line
/// (`{"type":"session","version":3,...}`) followed by one JSON record per
/// line; records form a tree through [SessionRecord.parentId], and `leaf`
/// records mark navigation of the active branch.
library;

import '../context.dart';
import '../types.dart';

/// The session header — always the first line of a JSONL session file.
///
/// Ported from pi's `SessionHeader` (version 3).
final class SessionHeader {
  /// Creates a [SessionHeader].
  const SessionHeader({
    required this.id,
    required this.timestamp,
    required this.cwd,
    this.parentSessionPath,
    this.metadata,
  });

  /// On-disk format version. Only version 3 is supported.
  static const version = 3;

  /// Unique session id.
  final String id;

  /// When the session was created.
  final DateTime timestamp;

  /// Working directory the session belongs to.
  final String cwd;

  /// Path of the session this one was forked from, if any.
  final String? parentSessionPath;

  /// Free-form application metadata.
  final Map<String, dynamic>? metadata;

  /// Serializes to the header JSON line (without the trailing newline).
  Map<String, dynamic> toJson() => {
    'type': 'session',
    'version': version,
    'id': id,
    'timestamp': timestamp.toIso8601String(),
    'cwd': cwd,
    if (parentSessionPath != null) 'parentSession': parentSessionPath,
    if (metadata != null) 'metadata': metadata,
  };

  /// Deserializes and validates a header JSON map.
  ///
  /// Throws [FormatException] on any invalid field, mirroring pi's
  /// `parseHeaderLine` validation.
  factory SessionHeader.fromJson(Map<String, dynamic> json) {
    FormatException invalid(String message) =>
        FormatException('Invalid session header: $message');
    if (json['type'] != 'session') {
      throw invalid('first line is not a valid session header');
    }
    if (json['version'] != version) {
      throw invalid('unsupported session version');
    }
    if (json['id'] is! String || (json['id'] as String).isEmpty) {
      throw invalid('session header is missing id');
    }
    if (json['timestamp'] is! String || (json['timestamp'] as String).isEmpty) {
      throw invalid('session header is missing timestamp');
    }
    if (json['cwd'] is! String || (json['cwd'] as String).isEmpty) {
      throw invalid('session header is missing cwd');
    }
    final parentSession = json['parentSession'];
    if (parentSession != null && parentSession is! String) {
      throw invalid('session header parentSession must be a string');
    }
    final metadata = json['metadata'];
    if (metadata != null && metadata is! Map<String, dynamic>) {
      throw invalid('session header metadata must be an object');
    }
    return SessionHeader(
      id: json['id'] as String,
      timestamp: DateTime.parse(json['timestamp'] as String),
      cwd: json['cwd'] as String,
      parentSessionPath: parentSession as String?,
      metadata: metadata as Map<String, dynamic>?,
    );
  }
}

/// One entry in the append-only session tree.
///
/// Sealed counterpart of pi's `SessionTreeEntry` discriminated union. Every
/// record has a unique [id], an optional [parentId] forming the tree, and a
/// [timestamp]. Dispatch on the concrete type (or [type]) to read the
/// payload.
sealed class SessionRecord {
  /// Creates a [SessionRecord].
  const SessionRecord({
    required this.id,
    required this.parentId,
    required this.timestamp,
  });

  /// The type discriminator written to JSON (pi's `type` field).
  String get type;

  /// Unique record id (short random id generated by the storage).
  final String id;

  /// Id of the parent record, or `null` for a tree root.
  final String? parentId;

  /// When the record was created.
  final DateTime timestamp;

  /// Serializes to a JSON map with the `type` discriminator (pi shape).
  Map<String, dynamic> toJson() => {
    'type': type,
    'id': id,
    'parentId': parentId,
    'timestamp': timestamp.toIso8601String(),
    ...payloadJson(),
  };

  /// Type-specific fields merged into [toJson] by subclasses.
  Map<String, dynamic> payloadJson();

  /// Deserializes a record JSON map, dispatching on `type`.
  ///
  /// Throws [FormatException] for unknown types or invalid base fields,
  /// mirroring pi's `parseEntryLine` validation.
  factory SessionRecord.fromJson(Map<String, dynamic> json) {
    FormatException invalid(String message) =>
        FormatException('Invalid session record: $message');
    final type = json['type'];
    if (type is! String) throw invalid('missing entry type');
    final id = json['id'];
    if (id is! String || id.isEmpty) throw invalid('missing entry id');
    final parentId = json['parentId'];
    if (parentId != null && parentId is! String) {
      throw invalid('invalid parentId');
    }
    final timestampRaw = json['timestamp'];
    if (timestampRaw is! String || timestampRaw.isEmpty) {
      throw invalid('missing timestamp');
    }
    final timestamp = DateTime.parse(timestampRaw);
    return switch (type) {
      'message' => MessageRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        message: messageFromJson(
          (json['message'] as Map?)?.cast<String, dynamic>() ??
              const <String, dynamic>{},
        ),
      ),
      'thinking_level_change' => ThinkingLevelChangeRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        thinkingLevel: json['thinkingLevel'] as String? ?? 'off',
      ),
      'model_change' => ModelChangeRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        provider: json['provider'] as String? ?? '',
        modelId: json['modelId'] as String? ?? '',
      ),
      'active_tools_change' => ActiveToolsChangeRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        activeToolNames: [
          for (final name in (json['activeToolNames'] as List?) ?? const [])
            name as String,
        ],
      ),
      'compaction' => CompactionRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        summary: json['summary'] as String? ?? '',
        firstKeptEntryId: json['firstKeptEntryId'] as String? ?? '',
        tokensBefore: json['tokensBefore'] as int? ?? 0,
        details: json['details'],
        fromHook: json['fromHook'] as bool?,
      ),
      'branch_summary' => BranchSummaryRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        fromId: json['fromId'] as String? ?? '',
        summary: json['summary'] as String? ?? '',
        details: json['details'],
        fromHook: json['fromHook'] as bool?,
      ),
      'custom' => CustomRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        customType: json['customType'] as String? ?? '',
        data: json['data'],
      ),
      'checkpoint' => CheckpointRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        messageCount: json['messageCount'] as int? ?? 0,
        goal: json['goal'] as String?,
      ),
      'custom_message' => CustomMessageRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        customType: json['customType'] as String? ?? '',
        content: _parseCustomMessageContent(json['content']),
        display: json['display'] as bool? ?? false,
        details: json['details'],
      ),
      'label' => LabelRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        targetId: json['targetId'] as String? ?? '',
        label: json['label'] as String?,
      ),
      'session_info' => SessionInfoRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        name: json['name'] as String?,
      ),
      'leaf' => LeafRecord(
        id: id,
        parentId: parentId as String?,
        timestamp: timestamp,
        targetId: json['targetId'] as String?,
      ),
      _ => throw invalid('unknown entry type: $type'),
    };
  }
}

Object _parseCustomMessageContent(Object? content) {
  if (content is String) return content;
  return [
    for (final block in (content as List?) ?? const [])
      ContentBlock.fromJson((block as Map).cast<String, dynamic>()),
  ];
}

/// A conversation message appended to the tree.
///
/// Ported from pi's `MessageEntry`.
final class MessageRecord extends SessionRecord {
  /// Creates a [MessageRecord].
  const MessageRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.message,
  });

  /// The conversation message (user, assistant, or tool result).
  final Message message;

  @override
  String get type => 'message';

  @override
  Map<String, dynamic> payloadJson() => {'message': message.toJson()};
}

/// Records a change of the model's thinking level.
///
/// Ported from pi's `ThinkingLevelChangeEntry`.
final class ThinkingLevelChangeRecord extends SessionRecord {
  /// Creates a [ThinkingLevelChangeRecord].
  const ThinkingLevelChangeRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.thinkingLevel,
  });

  /// The new thinking level (e.g. `off`, `low`, `high`).
  final String thinkingLevel;

  @override
  String get type => 'thinking_level_change';

  @override
  Map<String, dynamic> payloadJson() => {'thinkingLevel': thinkingLevel};
}

/// Records a change of the active model.
///
/// Ported from pi's `ModelChangeEntry`.
final class ModelChangeRecord extends SessionRecord {
  /// Creates a [ModelChangeRecord].
  const ModelChangeRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.provider,
    required this.modelId,
  });

  /// The provider id (e.g. `anthropic`).
  final String provider;

  /// The model id.
  final String modelId;

  @override
  String get type => 'model_change';

  @override
  Map<String, dynamic> payloadJson() => {
    'provider': provider,
    'modelId': modelId,
  };
}

/// Records a change of the active tool set.
///
/// Ported from pi's `ActiveToolsChangeEntry`.
final class ActiveToolsChangeRecord extends SessionRecord {
  /// Creates an [ActiveToolsChangeRecord].
  const ActiveToolsChangeRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.activeToolNames,
  });

  /// Names of the tools active from this point on.
  final List<String> activeToolNames;

  @override
  String get type => 'active_tools_change';

  @override
  Map<String, dynamic> payloadJson() => {'activeToolNames': activeToolNames};
}

/// Marks a compaction point: [summary] replaces everything before
/// [firstKeptEntryId] when the context is rebuilt.
///
/// Ported from pi's `CompactionEntry`. Written by the compaction pipeline
/// (a later phase); the record type is defined here so the tree and context
/// projection already understand it.
final class CompactionRecord extends SessionRecord {
  /// Creates a [CompactionRecord].
  const CompactionRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.summary,
    required this.firstKeptEntryId,
    required this.tokensBefore,
    this.details,
    this.fromHook,
  });

  /// LLM-generated summary of the compacted history.
  final String summary;

  /// Id of the first record kept verbatim after the summary.
  final String firstKeptEntryId;

  /// Token count of the context before compaction.
  final int tokensBefore;

  /// Optional structured details (e.g. file operations performed).
  final Object? details;

  /// Whether the compaction was triggered by a hook rather than the loop.
  final bool? fromHook;

  @override
  String get type => 'compaction';

  @override
  Map<String, dynamic> payloadJson() => {
    'summary': summary,
    'firstKeptEntryId': firstKeptEntryId,
    'tokensBefore': tokensBefore,
    if (details != null) 'details': details,
    if (fromHook != null) 'fromHook': fromHook,
  };
}

/// Marks a branch the conversation navigated away from, with an optional
/// [summary] projected into the context of the new branch.
///
/// Ported from pi's `BranchSummaryEntry`.
final class BranchSummaryRecord extends SessionRecord {
  /// Creates a [BranchSummaryRecord].
  const BranchSummaryRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.fromId,
    required this.summary,
    this.details,
    this.fromHook,
  });

  /// Id of the record the conversation returned to.
  final String fromId;

  /// Summary of the abandoned branch (empty when none was generated).
  final String summary;

  /// Optional structured details.
  final Object? details;

  /// Whether the navigation was triggered by a hook.
  final bool? fromHook;

  @override
  String get type => 'branch_summary';

  @override
  Map<String, dynamic> payloadJson() => {
    'fromId': fromId,
    'summary': summary,
    if (details != null) 'details': details,
    if (fromHook != null) 'fromHook': fromHook,
  };
}

/// Marks a self-service context checkpoint created by the `checkpoint` tool
/// so a later `rewind` can collapse the exploratory detour into a report.
///
/// Ported from oh-my-pi's checkpoint feature (`packages/coding-agent/src/
/// tools/checkpoint.ts`), where the mark is in-memory only; here the mark is
/// a tree record so it survives in the session log. The record anchors the
/// branch point: [messageCount] is the in-memory transcript length at the
/// mark (AFTER the checkpoint tool result was appended, omp semantics), and
/// the record's own [id] is the session-tree anchor the rewind navigates
/// back to. The record itself projects to nothing in model context.
final class CheckpointRecord extends SessionRecord {
  /// Creates a [CheckpointRecord].
  const CheckpointRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.messageCount,
    this.goal,
  });

  /// In-memory message count at the checkpoint (the rewind prune anchor).
  final int messageCount;

  /// Optional investigation goal text given by the model.
  final String? goal;

  @override
  String get type => 'checkpoint';

  @override
  Map<String, dynamic> payloadJson() => {
    'messageCount': messageCount,
    if (goal != null) 'goal': goal,
  };
}

/// An application-defined record that is omitted from model context by
/// default.
///
/// Ported from pi's `CustomEntry`.
final class CustomRecord extends SessionRecord {
  /// Creates a [CustomRecord].
  const CustomRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.customType,
    this.data,
  });

  /// Application-defined discriminator.
  final String customType;

  /// Application-defined payload.
  final Object? data;

  @override
  String get type => 'custom';

  @override
  Map<String, dynamic> payloadJson() => {
    'customType': customType,
    if (data != null) 'data': data,
  };
}

/// An application-defined record that projects into model context as a user
/// message.
///
/// Ported from pi's `CustomMessageEntry`.
final class CustomMessageRecord extends SessionRecord {
  /// Creates a [CustomMessageRecord].
  const CustomMessageRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.customType,
    required this.content,
    required this.display,
    this.details,
  });

  /// Application-defined discriminator.
  final String customType;

  /// Message content: a [String] or a `List<ContentBlock>` of
  /// [TextContent]/[ImageContent].
  final Object content;

  /// Whether the message is shown in the UI (does not affect context).
  final bool display;

  /// Optional structured details.
  final Object? details;

  @override
  String get type => 'custom_message';

  @override
  Map<String, dynamic> payloadJson() => {
    'customType': customType,
    'content': content is String
        ? content
        : [for (final block in content as List<ContentBlock>) block.toJson()],
    'display': display,
    if (details != null) 'details': details,
  };
}

/// Attaches (or removes, when [label] is null) a human-readable label to
/// another record, e.g. a bookmark in the tree UI.
///
/// Ported from pi's `LabelEntry`.
final class LabelRecord extends SessionRecord {
  /// Creates a [LabelRecord].
  const LabelRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    required this.targetId,
    this.label,
  });

  /// Id of the record being labeled.
  final String targetId;

  /// The label text; `null` (or empty/whitespace) removes the label.
  final String? label;

  @override
  String get type => 'label';

  @override
  Map<String, dynamic> payloadJson() => {
    'targetId': targetId,
    if (label != null) 'label': label,
  };
}

/// Records session-level information such as a display name.
///
/// Ported from pi's `SessionInfoEntry` (legacy `session_info` type name
/// kept for compatibility).
final class SessionInfoRecord extends SessionRecord {
  /// Creates a [SessionInfoRecord].
  const SessionInfoRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    this.name,
  });

  /// Display name of the session.
  final String? name;

  @override
  String get type => 'session_info';

  @override
  Map<String, dynamic> payloadJson() => {if (name != null) 'name': name};
}

/// Marks the active leaf of the tree after a branch navigation.
///
/// Ported from pi's `LeafEntry`. Appended by the storage when the session
/// moves to a different branch; [targetId] is the new leaf (or `null` for
/// the tree root).
final class LeafRecord extends SessionRecord {
  /// Creates a [LeafRecord].
  const LeafRecord({
    required super.id,
    required super.parentId,
    required super.timestamp,
    this.targetId,
  });

  /// The new active leaf, or `null` for the tree root.
  final String? targetId;

  @override
  String get type => 'leaf';

  @override
  Map<String, dynamic> payloadJson() => {'targetId': targetId};
}
