#!/usr/bin/env bash
# Copyright (c) 2026, the Flutter Agent Harness authors.
# Use of this source code is governed by a MIT license that can be found
# in the LICENSE file.
#
# gh-1296 NG1: every lockfile in the repo is committed and enforced.
#
# ONE inventory list (below) drives every check — a new lockfile joins the
# list, it is never discovered per-file after a red build (#1265/#1296 class).
#
#   inventory  — each listed lockfile exists, is git-tracked, and is NOT
#                gitignored (a gitignored/missing lockfile fails CI); plus
#                the gh-1303 path-pin sync: flutter_app/pubspec.lock's pin
#                of this repo (path dependency) must equal the root
#                pubspec.yaml version — a stale pin fails every
#                `flutter pub get --enforce-lockfile` consumer (pages.yml
#                web demo, ci.yml flutter legs) the moment it lands
#   pod-sync   — every native (native_build: true) iOS/macOS Flutter plugin
#                resolved by the committed pubspec.lock has its pod in the
#                platform's Podfile.lock, AT THE PODSPEC'S VERSION. Catches
#                the gh-1274 class (a native plugin lands in
#                pubspec.yaml/lock but the Podfile.locks are never
#                regenerated) AND the version-skew class this PR itself
#                fixed (pre-rework: pubspec.lock pinned flutter_gemma 1.11.3
#                while the pods were 1.8.0/1.7.0 — presence-only checking
#                stayed green through it). The pod version in Podfile.lock
#                must match the resolved plugin podspec's s.version — the
#                same file `pod install` resolves from — NOT the pubspec
#                version: vendored/beta plugins legitimately ship pod
#                versions that differ from the Dart package version
#                (flutter_inappwebview_ios: pod 0.0.1, pub 1.2.0-beta.3).
#                Requires flutter_app/.flutter-plugins-dependencies
#                (generated by `flutter pub get`; run this after it, as
#                ci.yml does).
#   all        — both (default)
#   list       — print the inventory, one path per line (consumed by
#                auto_release.sh's release dirty-tree gate, gh-1299 NG1)
#
# Self-test (synthetic fixtures, no flutter needed):
#   scripts/check_lockfiles_selftest.sh   — wired into ci.yml Static gates
#                                           AND re-run in the dart legs via
#                                           test/scripts/check_lockfiles_gate_test.dart
#
# Environment overrides (used by the selftest; normal runs need nothing):
#   FAH_REPO_ROOT       repo root (default: script's grandparent)
#   FAH_PLUGINS_FILE    .flutter-plugins-dependencies path for pod-sync

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${FAH_REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"

# ── THE inventory (gh-1296 NG1: one list, not per-file discoveries) ──────
# Every lockfile whose drift can break a build must appear here exactly once.
LOCKFILES=(
  "flutter_app/pubspec.lock"        # app dependency pins (#1265)
  "flutter_app/ios/Podfile.lock"    # iOS CocoaPods pins (#1296)
  "flutter_app/macos/Podfile.lock"  # macOS CocoaPods pins (#1296)
  # PR #1298 rework — the rest of the NG1 "every lockfile in the repo" set
  # (all tracked today; the inventory keeps them that way):
  "vendor/flutter_inappwebview_macos/macos/flutter_inappwebview_macos/Package.resolved"  # SwiftPM pins of the vendored macOS plugin
  "browser_ext/e2e/package-lock.json"   # npm pins the browser-ext e2e legs `npm ci` against
  "office_addin/e2e/package-lock.json"  # npm pins the office-addin e2e legs `npm ci` against
  "vendor/wasm_run/native/Cargo.lock"   # vendored wasm native build crate pins
)

cd "$REPO_ROOT"

mode="${1:-all}"
case "$mode" in
  inventory|pod-sync|all) ;;
  # gh-1299 NG1: print the inventory, one path per line — consumers that
  # must act on EVERY committed lockfile (auto_release.sh's dirty-tree
  # release gate) read the list from here so the inventory stays ONE list.
  list)
    printf '%s\n' "${LOCKFILES[@]}"
    exit 0
    ;;
  *)
    echo "usage: $0 [inventory|pod-sync|all|list]" >&2
    exit 64
    ;;
esac

fail=0

# ── inventory: exists + tracked + not gitignored ─────────────────────────
if [ "$mode" = "inventory" ] || [ "$mode" = "all" ]; then
  for f in "${LOCKFILES[@]}"; do
    if [ ! -f "$f" ]; then
      echo "::error::lockfile MISSING from the working tree: $f — restore it (git checkout -- $f) or regenerate it and commit"
      fail=1
      continue
    fi
    if ! git ls-files --error-unmatch "$f" >/dev/null 2>&1; then
      echo "::error::lockfile not tracked by git: $f — git add $f and commit (gh-1296 NG1)"
      fail=1
    fi
    if git check-ignore -q --no-index "$f"; then
      # --no-index: a TRACKED file still matching an ignore pattern is the
      # #1265/#1296 trap — one future `git rm --cached` and drift goes dark
      echo "::error::lockfile is GITIGNORED: $f — remove the ignore pattern; a lockfile that drifts invisibly is how #1265/#1296 happened"
      fail=1
    fi
  done
  if [ "$fail" -eq 0 ]; then
    echo "lockfile inventory ok: ${#LOCKFILES[@]} files tracked, none ignored"
  fi

  # gh-1303: the app lock pins THIS repo as a path dependency — when its
  # version diverges from the root pubspec (exactly what a version bump
  # without a lock regen produces), or the pin is MISSING entirely (e.g. a
  # merge conflict resolved by dropping the hunk), every `flutter pub get
  # --enforce-lockfile` consumer (pages.yml web demo build, ci.yml flutter
  # legs, the packaging scripts) reds with "Unable to satisfy pubspec.yaml
  # using pubspec.lock". The release bump re-pins the lock itself
  # (scripts/auto_release.sh); this catches every other path to the same
  # drift at PR time. Tolerant ONLY for shapes with nothing to compare: a
  # root pubspec without a `version:` key (fixtures/packages) skips
  # silently — but in the real-repo shape (root has a version + the lock
  # exists) a missing harness entry REDS: it is the same consumer-breaking
  # drift class, never a healthy state here. python3 is guarded like the
  # pod-sync check (`|| fail=1` + ::error::) so a broken/missing python3
  # cannot kill the inventory run unannotated; both YAML extractions (root
  # version + lock pin) live in that one heredoc.
  if [ -f pubspec.yaml ] && grep -q '^version:' pubspec.yaml && [ -f flutter_app/pubspec.lock ]; then
    pin_state="$(python3 - pubspec.yaml flutter_app/pubspec.lock <<'PY'
import sys


def pubspec_version(path):
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("version:"):
                return line.split("version:", 1)[1].strip().strip('"').strip("'")
    return ""


def lock_pin(path):
    inside = False
    with open(path, encoding="utf-8") as f:
        for line in f.read().splitlines():
            if line.rstrip() == "  flutter_agent_harness:":
                inside = True
                continue
            if inside and line.startswith("  ") and not line.startswith("    "):
                break  # next package entry — the pin was not inside this one
            if inside and line.strip().startswith("version:"):
                return line.split("version:", 1)[1].strip().strip('"')
    return ""


print(pubspec_version(sys.argv[1]))
print(lock_pin(sys.argv[2]))
PY
)" || {
      echo "::error::path-pin check could not run (python3 failed) — the gh-1303 pin-sync check needs python3 (the pod-sync check already does); fix python3 and re-run"
      fail=1
    }
    if [ -n "$pin_state" ]; then
      root_version="$(sed -n '1p' <<<"$pin_state")"
      lock_pin="$(sed -n '2p' <<<"$pin_state")"
      if [ -z "$lock_pin" ]; then
        echo "::error::flutter_app/pubspec.lock has NO flutter_agent_harness entry but pubspec.yaml is $root_version (gh-1303 class) — the app depends on this repo via path, so a lock without the pin fails every 'flutter pub get --enforce-lockfile' consumer (pages.yml web demo, ci.yml flutter legs) exactly like a stale pin. Re-pin the lock and commit: cd flutter_app && flutter pub get"
        fail=1
      elif [ "$lock_pin" != "$root_version" ]; then
        echo "::error::flutter_app/pubspec.lock pins flutter_agent_harness $lock_pin but pubspec.yaml is $root_version (gh-1303 class) — every 'flutter pub get --enforce-lockfile' consumer (pages.yml web demo, ci.yml flutter legs) would red on main. Re-pin the lock and commit: cd flutter_app && flutter pub get"
        fail=1
      elif [ "$fail" -eq 0 ]; then
        echo "path-pin ok: flutter_app/pubspec.lock pins flutter_agent_harness at the pubspec version ($root_version)"
      fi
    fi
  fi
fi
fi

# ── pod-sync: native darwin plugins vs Podfile.lock ──────────────────────
if [ "$mode" = "pod-sync" ] || [ "$mode" = "all" ]; then
  PLUGINS_FILE="${FAH_PLUGINS_FILE:-flutter_app/.flutter-plugins-dependencies}"
  if [ ! -f "$PLUGINS_FILE" ]; then
    echo "::error::$PLUGINS_FILE not found — run 'cd flutter_app && flutter pub get --enforce-lockfile' first (the pod-sync check reads the resolved plugin set)"
    exit 1
  fi

  python3 - "$PLUGINS_FILE" <<'PYEOF' || fail=1
import json, os, re, sys

plugins_file, repo_root = sys.argv[1], os.getcwd()
platforms = {"ios": "flutter_app/ios/Podfile.lock", "macos": "flutter_app/macos/Podfile.lock"}

try:
    with open(plugins_file) as f:
        deps = json.load(f)
except (OSError, ValueError) as e:
    print(f"::error::{plugins_file} is missing, unreadable, or not valid JSON ({type(e).__name__}) — re-run 'cd flutter_app && flutter pub get --enforce-lockfile' to regenerate it, then re-run this gate")
    sys.exit(1)

pod_names, pod_versions = {}, {}
for plat, lockfile in platforms.items():
    if not os.path.isfile(lockfile):
        print(f"::error::{lockfile} not found — it must exist (gh-1296 NG1)")
        sys.exit(1)
    text = open(lockfile).read()
    section = text.split("DEPENDENCIES:")[0]
    # Top-level pods only — `/`-separated subspecs stay excluded, but pod
    # names with dashes (vendored podspecs, Google-*-SDK style) are captured
    # (PR #1298 rework thread 4: `[A-Za-z0-9_.]` missed swift-collections and
    # would false-red a dashed pod while present).
    pod_names[plat] = set(re.findall(r"^  - ([A-Za-z0-9_.+-]+) \(", section, re.M))
    pod_versions[plat] = {
        m.group(1): m.group(2)
        for m in re.finditer(r"^  - ([A-Za-z0-9_.+-]+) \(([^)]+)\):?$", section, re.M)
    }

missing, stale = [], []
for plat, lockfile in platforms.items():
    for p in deps.get("plugins", {}).get(plat, []):
        # dart-plugin-class-only plugins (native_build: false) never produce pods
        if not p.get("native_build", True):
            continue
        name, base = p["name"], p["path"]
        if not os.path.isabs(base):
            base = os.path.join(repo_root, base)
        pod = None
        spec_version = None
        for sub in (plat, "darwin"):
            d = os.path.join(base, sub)
            if not os.path.isdir(d):
                continue
            for spec in sorted(os.listdir(d)):
                if not spec.endswith(".podspec"):
                    continue
                text = open(os.path.join(d, spec)).read()
                m = re.search(r"^\s*s\.name\s*=\s*'([^']+)'", text, re.M)
                pod = m.group(1) if m else spec[: -len(".podspec")]
                v = re.search(r"^\s*s\.version\s*=\s*['\"]([^'\"]+)['\"]", text, re.M)
                spec_version = v.group(1) if v else None
                break
            if pod:
                break
        if pod is None:
            pod = name  # no podspec shipped — assume the default name
        if pod not in pod_names[plat]:
            missing.append((plat, name, pod))
        elif (
            spec_version is not None
            and pod in pod_versions[plat]
            and pod_versions[plat][pod] != spec_version
        ):
            # PR #1298 rework thread 3: presence-only checking stayed green
            # while the pod sat at a stale version (flutter_gemma: pubspec
            # 1.11.3, ios pod 1.8.0 / macos 1.7.0 — the Dart side new, the
            # native side compiling old plugin code). Compare against the
            # podspec's own s.version — what `pod install` resolves from —
            # not the pubspec version (vendored/beta pods legitimately
            # differ from the Dart package version).
            stale.append((plat, name, pod, pod_versions[plat][pod], spec_version))

if missing:
    print("::error::Podfile.lock drift — native plugins resolved by pubspec.lock have no pod in the committed Podfile.lock (gh-1296 NG1). Regenerate and commit:")
    for plat, plugin, pod in missing:
        print(f"::error::  {plat}: plugin {plugin} (pod '{pod}' missing from flutter_app/{plat}/Podfile.lock)")
    print("::error::fix: cd flutter_app/ios && pod install --repo-update && cd ../macos && pod install --repo-update; git add both Podfile.lock files")
    sys.exit(1)

if stale:
    print("::error::Podfile.lock pod VERSION drift — a native plugin's pod is pinned at a stale version while the resolved plugin podspec moved on (the pre-rework flutter_gemma skew). Regenerate and commit:")
    for plat, plugin, pod, locked, declared in stale:
        print(f"::error::  {plat}: plugin {plugin} pod '{pod}' is {locked} in flutter_app/{plat}/Podfile.lock but the resolved podspec declares {declared}")
    print("::error::fix: cd flutter_app/ios && pod install --repo-update && cd ../macos && pod install --repo-update; git add both Podfile.lock files")
    sys.exit(1)
print("pod-sync ok: every native darwin plugin has its pod committed at the podspec version")
PYEOF
fi

if [ "$fail" -ne 0 ]; then
  echo "lockfile gate FAILED" >&2
  exit 1
fi
echo "lockfile gate passed"
