#!/usr/bin/env dart
// Generates site/install.sh and site/install.ps1 from site/install-config.yaml.
//
// Usage:
//   dart run scripts/gen_installers.dart
//
// After editing site/install-config.yaml, rerun this script and commit the
// generated installer files. Do not edit install.sh / install.ps1 by hand.

import 'dart:io';

import 'package:yaml/yaml.dart';

const _configPath = 'site/install-config.yaml';
const _shTemplatePath = 'site/install.sh.template';
const _psTemplatePath = 'site/install.ps1.template';
const _shOut = 'site/install.sh';
const _psOut = 'site/install.ps1';

final _generatedHeader =
    '''
# ═══════════════════════════════════════════════════════════════════════════
#  DO NOT EDIT THIS FILE BY HAND. It is generated from site/install-config.yaml
#  by `dart run scripts/gen_installers.dart`.
# ═══════════════════════════════════════════════════════════════════════════
'''
        .trim();

void main() {
  final config = loadYaml(File(_configPath).readAsStringSync()) as YamlMap;
  final providers = config['providers'] as YamlList;
  final modes = config['modes'] as YamlList;
  final approvalModes = config['approval_modes'] as YamlList;

  final sh = File(_shTemplatePath)
      .readAsStringSync()
      .replaceFirst('# {{GENERATED_HEADER}}', _generatedHeader)
      .replaceFirst('{{PROVIDER_MENU}}', _shProviderMenu(providers))
      .replaceFirst('{{PROVIDER_CASES}}', _shProviderCases(providers))
      .replaceFirst('{{MODE_MENU}}', _shModeMenu(modes))
      .replaceFirst('{{MODE_CASES}}', _shModeCases(modes))
      .replaceFirst('{{APPROVAL_MENU}}', _shApprovalMenu(approvalModes))
      .replaceFirst('{{APPROVAL_CASES}}', _shApprovalCases(approvalModes));

  final ps = File(_psTemplatePath)
      .readAsStringSync()
      .replaceFirst('# {{GENERATED_HEADER}}', _generatedHeader)
      .replaceFirst('{{PROVIDER_MENU}}', _psProviderMenu(providers))
      .replaceFirst('{{PROVIDER_SWITCH}}', _psProviderSwitch(providers))
      .replaceFirst('{{MODE_MENU}}', _psModeMenu(modes))
      .replaceFirst('{{MODE_SWITCH}}', _psModeSwitch(modes))
      .replaceFirst('{{APPROVAL_MENU}}', _psApprovalMenu(approvalModes))
      .replaceFirst('{{APPROVAL_SWITCH}}', _psApprovalSwitch(approvalModes));

  File(_shOut).writeAsStringSync(sh);
  File(_psOut).writeAsStringSync(ps);

  print('Generated $_shOut and $_psOut from $_configPath');
}

// ── Shell fragments ─────────────────────────────────────────────────────────

String _shProviderMenu(YamlList providers) {
  final b = StringBuffer();
  b.writeln(r'# Provider menu');
  for (var i = 0; i < providers.length; i++) {
    final p = providers[i];
    final note = p['note'] ?? '';
    final rec = p['recommended'] == true ? '   (recommended)' : '';
    b.writeln('say "  ${i + 1}) ${p['name']}  — $note$rec"');
  }
  b.writeln(r'say ""');
  b.writeln(r'provider_choice=""');
  b.writeln(r'while true; do');
  b.write(r'  ask provider_choice "Pick a provider [1-');
  b.write(providers.length);
  b.writeln(r']" "1"');
  b.writeln(r'  case "$provider_choice" in');
  for (var i = 0; i < providers.length; i++) {
    final p = providers[i];
    b.writeln(
      '    ${i + 1}|${p['id']}) provider="${p['id']}"; provider_kind="${p['kind']}"; break ;;',
    );
  }
  b.write(r'    *) warn "enter 1-');
  b.write(providers.length);
  b.writeln(r'" ;;');
  b.writeln(r'  esac');
  b.writeln(r'done');
  return b.toString();
}

String _shProviderCases(YamlList providers) {
  final b = StringBuffer();
  b.writeln(r'# Model selection');
  b.writeln(r'model=""');
  b.writeln(r'base_url=""');
  b.writeln(r'case "$provider" in');
  for (var i = 0; i < providers.length; i++) {
    final p = providers[i];
    b.writeln('  ${p['id']})');
    if (p['custom'] == true) {
      b.writeln(r'    say ""');
      b.writeln(
        r'    ask base_url "Custom base URL (e.g. http://localhost:11434/v1)"',
      );
      b.writeln(r'    ask model "Model id on that endpoint"');
      b.writeln('    key_var="${p['key_var']}"');
    } else {
      b.writeln(r'    say ""');
      b.writeln('    say "  ${p['name']} models:"');
      final models = p['models'] as YamlList;
      for (var j = 0; j < models.length; j++) {
        final m = models[j];
        final label = m['label'] ?? m['id'];
        final rec = m['recommended'] == true ? '   (recommended)' : '';
        b.writeln('    say "    ${j + 1}) $label$rec"');
      }
      b.writeln(
        '    say "    ${models.length + 1}) other — enter model id manually"',
      );
      b.writeln(r'    while true; do');
      b.writeln(r'      ask model "Pick a model" "1"');
      b.writeln(r'      case "$model" in');
      for (var j = 0; j < models.length; j++) {
        final m = models[j];
        b.writeln('        ${j + 1}) model="${m['id']}"; break ;;');
      }
      b.writeln(
        '        ${models.length + 1}) ask model "Enter the ${p['name']} model id"; break ;;',
      );
      b.write(r'        *) warn "enter 1-');
      b.write(models.length + 1);
      b.writeln(r'" ;;');
      b.writeln(r'      esac');
      b.writeln(r'    done');
      b.writeln('    base_url="${p['base_url']}"');
      b.writeln('    key_var="${p['key_var']}"');
    }
    b.writeln(r'    ;;');
  }
  b.writeln(r'esac');
  return b.toString();
}

String _shModeMenu(YamlList modes) {
  final b = StringBuffer();
  b.writeln(r'# Mode selection');
  b.writeln(r'say ""');
  b.writeln(r'say "  Agent modes:"');
  for (var i = 0; i < modes.length; i++) {
    final m = modes[i];
    final note = m['note'] ?? '';
    final rec = m['default'] == true ? ' (default)' : '';
    b.writeln('say "    ${i + 1}) ${m['id']}$rec  — $note"');
  }
  return b.toString();
}

String _shModeCases(YamlList modes) {
  final b = StringBuffer();
  b.writeln(r'mode=""');
  b.writeln(r'while true; do');
  b.writeln(r'  ask mode "Pick a mode" "1"');
  b.writeln(r'  case "$mode" in');
  for (var i = 0; i < modes.length; i++) {
    final m = modes[i];
    b.writeln('    ${i + 1}|${m['id']}) mode="${m['id']}"; break ;;');
  }
  b.write(r'    *) warn "enter 1-');
  b.write(modes.length);
  b.writeln(r'" ;;');
  b.writeln(r'  esac');
  b.writeln(r'done');
  return b.toString();
}

String _shApprovalMenu(YamlList approvalModes) {
  final b = StringBuffer();
  b.writeln(r'# Approval mode');
  b.writeln(r'say ""');
  b.writeln(r'say "  Tool approval:"');
  for (var i = 0; i < approvalModes.length; i++) {
    final a = approvalModes[i];
    final note = a['note'] ?? '';
    final rec = a['default'] == true ? ' (default)' : '';
    b.writeln('say "    ${i + 1}) ${a['id']}$rec  — $note"');
  }
  return b.toString();
}

String _shApprovalCases(YamlList approvalModes) {
  final b = StringBuffer();
  b.writeln(r'approval=""');
  b.writeln(r'while true; do');
  b.writeln(r'  ask approval "Pick an approval mode" "1"');
  b.writeln(r'  case "$approval" in');
  for (var i = 0; i < approvalModes.length; i++) {
    final a = approvalModes[i];
    b.writeln('    ${i + 1}|${a['id']}) approval="${a['id']}"; break ;;');
  }
  b.write(r'    *) warn "enter 1-');
  b.write(approvalModes.length);
  b.writeln(r'" ;;');
  b.writeln(r'  esac');
  b.writeln(r'done');
  return b.toString();
}

// ── PowerShell fragments ────────────────────────────────────────────────────
// In this section every `$` that should appear in the generated .ps1 file is
// written as `\$` so Dart's string interpolation ignores it. Dart `${...}` is
// still used for values coming from install-config.yaml.

String _psProviderMenu(YamlList providers) {
  final b = StringBuffer();
  b.writeln('# Provider menu');
  for (var i = 0; i < providers.length; i++) {
    final p = providers[i];
    final note = p['note'] ?? '';
    final rec = p['recommended'] == true ? '   (recommended)' : '';
    b.writeln('Write-Host "  ${i + 1}) ${p['name']}  — $note$rec"');
  }
  b.writeln(r'Write-Host ""');
  final valid = <String>[];
  for (var i = 0; i < providers.length; i++) {
    valid.add('"${i + 1}"');
  }
  for (var i = 0; i < providers.length; i++) {
    valid.add('"${providers[i]['id']}"');
  }
  b.writeln(
    '\$providerChoice = Read-Choice "Pick a provider [1-${providers.length}]" @(${valid.join(', ')})',
  );
  return b.toString();
}

String _psProviderSwitch(YamlList providers) {
  final b = StringBuffer();
  b.writeln('switch -Regex (\$providerChoice) {');
  for (var i = 0; i < providers.length; i++) {
    final p = providers[i];
    b.writeln('    "^(${i + 1}|${p['id']})\$" {');
    b.writeln('        \$provider = "${p['id']}"');
    b.writeln('        \$providerKind = "${p['kind']}"');
    if (p['custom'] == true) {
      b.writeln(
        '        \$baseUrl = Read-Host "Custom base URL (e.g. http://localhost:11434/v1)"',
      );
      b.writeln('        \$model = Read-Host "Model id on that endpoint"');
      b.writeln('        \$keyVar = "${p['key_var']}"');
    } else {
      b.writeln(r'        Write-Host ""');
      b.writeln('        Write-Host "  ${p['name']} models:"');
      final models = p['models'] as YamlList;
      for (var j = 0; j < models.length; j++) {
        final m = models[j];
        final label = m['label'] ?? m['id'];
        final rec = m['recommended'] == true ? '   (recommended)' : '';
        b.writeln('        Write-Host "    ${j + 1}) $label$rec"');
      }
      b.writeln(
        '        Write-Host "    ${models.length + 1}) other — enter model id manually"',
      );
      final valid = List.generate(
        models.length + 1,
        (j) => '"${j + 1}"',
      ).join(', ');
      b.writeln(
        '        \$m = Read-Choice "Pick a model [1-${models.length + 1}]" @($valid)',
      );
      b.writeln('        switch (\$m) {');
      for (var j = 0; j < models.length; j++) {
        b.writeln('            "${j + 1}" { \$model = "${models[j]['id']}" }');
      }
      b.writeln(
        '            "${models.length + 1}" { \$model = Read-Host "Enter the ${p['name']} model id" }',
      );
      b.writeln(r'        }');
      b.writeln('        \$baseUrl = "${p['base_url']}"');
      b.writeln('        \$keyVar = "${p['key_var']}"');
    }
    b.writeln(r'    }');
  }
  b.writeln(r'}');
  return b.toString();
}

String _psModeMenu(YamlList modes) {
  final b = StringBuffer();
  b.writeln('# Mode selection');
  b.writeln(r'Write-Host ""');
  b.writeln(r'Write-Host "  Agent modes:"');
  for (var i = 0; i < modes.length; i++) {
    final m = modes[i];
    final note = m['note'] ?? '';
    final rec = m['default'] == true ? ' (default)' : '';
    b.writeln('Write-Host "    ${i + 1}) ${m['id']}$rec  — $note"');
  }
  return b.toString();
}

String _psModeSwitch(YamlList modes) {
  final b = StringBuffer();
  final valid = <String>[];
  for (var i = 0; i < modes.length; i++) {
    valid.add('"${i + 1}"');
    valid.add('"${modes[i]['id']}"');
  }
  b.writeln(
    '\$modeChoice = Read-Choice "Pick a mode [1-${modes.length}]" @(${valid.join(', ')})',
  );
  b.writeln('switch -Regex (\$modeChoice) {');
  for (var i = 0; i < modes.length; i++) {
    final m = modes[i];
    b.writeln('    "^(${i + 1}|${m['id']})\$" { \$mode = "${m['id']}" }');
  }
  b.writeln(r'}');
  return b.toString();
}

String _psApprovalMenu(YamlList approvalModes) {
  final b = StringBuffer();
  b.writeln('# Approval mode');
  b.writeln(r'Write-Host ""');
  b.writeln(r'Write-Host "  Tool approval:"');
  for (var i = 0; i < approvalModes.length; i++) {
    final a = approvalModes[i];
    final note = a['note'] ?? '';
    final rec = a['default'] == true ? ' (default)' : '';
    b.writeln('Write-Host "    ${i + 1}) ${a['id']}$rec  — $note"');
  }
  return b.toString();
}

String _psApprovalSwitch(YamlList approvalModes) {
  final b = StringBuffer();
  final valid = <String>[];
  for (var i = 0; i < approvalModes.length; i++) {
    valid.add('"${i + 1}"');
    valid.add('"${approvalModes[i]['id']}"');
  }
  b.writeln(
    '\$approvalChoice = Read-Choice "Pick an approval mode [1-${approvalModes.length}]" @(${valid.join(', ')})',
  );
  b.writeln('switch -Regex (\$approvalChoice) {');
  for (var i = 0; i < approvalModes.length; i++) {
    final a = approvalModes[i];
    b.writeln('    "^(${i + 1}|${a['id']})\$" { \$approval = "${a['id']}" }');
  }
  b.writeln(r'}');
  return b.toString();
}
