/// Pulls the bundled Codex model catalog from the official openai/codex
/// repository and writes a Dart source file with the parsed entries.
///
/// Run as part of the release pipeline (see AGENTS.md / ci.yml). The
/// generated file is checked in so the app can build without network
/// access — every release just needs the latest `models.json` reflected
/// in source.
///
/// Usage: `dart run scripts/sync_codex_models.dart`
///
/// Source URL points at openai/codex@main (the same source the
/// `codex-rs/models-manager` crate ships in its own bundled response).
/// Override via the first positional argument: a raw GitHub URL or a
/// local file path.
library;

import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

const _defaultSource =
    'https://raw.githubusercontent.com/openai/codex/main/'
    'codex-rs/models-manager/models.json';

/// The file this script generates. Relative to repo root.
const _outputPath = 'lib/src/providers/chatgpt_codex_models_data.dart';

void main(List<String> args) async {
  final source = args.isNotEmpty ? args.first : _defaultSource;
  print('Fetching $source …');
  final raw = await _fetch(source);
  print('  ${raw.length} bytes');

  final json = jsonDecode(raw);
  if (json is! Map) {
    throw const FormatException('models.json: root is not an object');
  }
  final models = json['models'];
  if (models is! List) {
    throw const FormatException('models.json: missing `models` array');
  }

  final entries = <_Entry>[];
  for (final m in models) {
    if (m is! Map) continue;
    final slug = m['slug'];
    final context = m['context_window'];
    // models.json doesn't carry a per-model output cap (the Codex backend
    // controls that). Use 16384 (the same default the picker uses for
    // openai-completions and the chatgpt-codex ProviderSpec).
    if (slug is! String) continue;
    entries.add(
      _Entry(
        slug: slug,
        contextWindow: context is int ? context : 0,
        maxTokens: 16384,
      ),
    );
  }
  if (entries.isEmpty) {
    throw const FormatException('models.json: no entries parsed');
  }

  final buffer = StringBuffer()
    ..writeln('/// AUTO-GENERATED by scripts/sync_codex_models.dart — do not edit.')
    ..writeln('///')
    ..writeln('/// Source: openai/codex@main/codex-rs/models-manager/models.json')
    ..writeln('/// Regenerate: `dart run scripts/sync_codex_models.dart`')
    ..writeln('///')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// One Codex model entry (mirror of codex-rs bundled model fields).')
    ..writeln('class CodexModelData {')
    ..writeln('  const CodexModelData({')
    ..writeln('    required this.slug,')
    ..writeln('    required this.contextWindow,')
    ..writeln('    required this.maxTokens,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  /// The model id (matches [Model.id] from the runtime API).')
    ..writeln('  final String slug;')
    ..writeln()
    ..writeln('  /// The context window the Codex backend reports (input cap).')
    ..writeln('  final int contextWindow;')
    ..writeln()
    ..writeln('  /// The output cap the Codex backend reports.')
    ..writeln('  final int maxTokens;')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Bundled Codex catalog as of generation time. Source of truth:')
    ..writeln('/// <https://github.com/openai/codex/blob/main/codex-rs/models-manager/models.json>.')
    ..writeln('const List<CodexModelData> chatGptCodexBundledModels = <CodexModelData>[');
  for (final e in entries) {
    buffer.writeln(
      '  CodexModelData(slug: ${_quote(e.slug)}, '
      'contextWindow: ${e.contextWindow}, '
      'maxTokens: ${e.maxTokens}),',
    );
  }
  buffer.writeln('];');
  buffer.writeln();
  buffer.writeln(
    '/// The Codex default model (the first [chatGptCodexBundledModels] entry, '
    'kept separate so the OAuth flow + the picker read the same answer).',
  );
  buffer.writeln(
    'const String chatGptCodexBundledDefault = '
    "'${entries.first.slug}';",
  );

  final out = File(_outputPath);
  await out.parent.create(recursive: true);
  await out.writeAsString(buffer.toString());
  print('Wrote ${entries.length} models to $_outputPath');
}

Future<String> _fetch(String source) async {
  if (source.startsWith('http://') || source.startsWith('https://')) {
    final response = await http
        .get(Uri.parse(source))
        .timeout(const Duration(seconds: 30));
    if (response.statusCode != 200) {
      throw HttpException(
        'HTTP ${response.statusCode} from $source',
        uri: Uri.parse(source),
      );
    }
    return response.body;
  }
  return File(source).readAsString();
}

class _Entry {
  const _Entry({
    required this.slug,
    required this.contextWindow,
    required this.maxTokens,
  });
  final String slug;
  final int contextWindow;
  final int maxTokens;
}

String _quote(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
